### ISSUE TITLE
Wilder Wild

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#312] opened 2023-09-23 02:14 UTC
### Mod Name

Wilder Wild

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/wilder-wild

### Describe the bug

Crash before title screen

### Steps to reproduce

Install Wilder Wilds

### Logs

https://gist.github.com/Its-Just-Luci/449d5bb4d09e165bbaa2a9887e53de8e

### Additional context

`[22Sep2023 09:25:11.563] [pool-4-thread-1/ERROR] [mixin/]: Critical injection failure: LVT in net/minecraft/world/item/AxeItem::m_6225_(Lnet/minecraft/world/item/context/UseOnContext;)Lnet/minecraft/world/InteractionResult; has incompatible changes at opcode 32 in callback mixin/frozenlib.axe.mixins.json:AxeItemMixin from mod (unknown)->@Inject::frozenlib$_axeBehaviors(Lnet/minecraft/world/item/context/UseOnContext;Lio/github/steelwoolmc/shadow/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/block/state/BlockState;Ljava/util/Optional;Ljava/util/Optional;Ljava/util/Optional;Lnet/minecraft/world/item/ItemStack;Ljava/util/Optional;)V.
 Expected: [Lnet/minecraft/world/level/Level;, Lnet/minecraft/core/BlockPos;, Lnet/minecraft/world/entity/player/Player;, Lnet/minecraft/world/level/block/state/BlockState;, Ljava/util/Optional;, Ljava/util/Optional;, Ljava/util/Optional;, Lnet/minecraft/world/item/ItemStack;, Ljava/util/Optional;]
    Found: [Lnet/minecraft/world/level/Level;, Lnet/minecraft/core/BlockPos;, Lnet/minecraft/world/entity/player/Player;, Lnet/minecraft/world/level/block/state/BlockState;, Ljava/util/Optional;]
Available: [Lnet/minecraft/world/level/Level;, Lnet/minecraft/core/BlockPos;, Lnet/minecraft/world/entity/player/Player;, Lnet/minecraft/world/level/block/state/BlockState;, Ljava/util/Optional;]
`

**Comment by Su5eD** [comment] 2023-09-23 07:26
Duplicate of #40

**Closed by Su5eD** 2023-09-23 07:26 UTC
Labels: compat
