### ISSUE TITLE
Carpet Injection failed

### ISSUE THREAD

**Issue by GMF331** [Sinytra/Connector#1251] opened 2024-07-20 14:19 UTC
### Mod Name

Carpet

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/carpet

### Minecraft version

1.20.1

### Describe the bug

Unable to load by the game

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/GMF331/e2916f7e7daa9bb04c7ac88d5e3f4fed.js

**Comment by Su5eD** [comment] 2024-07-20 15:04
Duplicate of https://github.com/Sinytra/Connector/issues/296

**Closed by Su5eD** 2024-07-20 15:04 UTC
Labels: compat
