### ISSUE TITLE
Craftify is not compatible

### ISSUE THREAD

**Issue by 2315506431** [Sinytra/Connector#980] opened 2024-04-06 15:37 UTC
### Mod Name

Craftify

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/craftify

### Minecraft version

1.20.1

### Describe the bug

Game won't start properly

### Steps to reproduce

1.Installation of Sinytra Connector and frontend
2.installation of Craftify and Fabric Language Kotlin
3.Click start, crash pop-up

### Logs

https://gist.github.com/2315506431/00b84d719eecf48b82c3cb13ab3d268c

**Comment by Su5eD** [comment] 2024-04-06 16:33
Duplicate of #959

**Closed by Su5eD** 2024-04-06 16:33 UTC
Labels: compat
