### ISSUE TITLE
Creative Tab Loop Found when using Zeta

### ISSUE THREAD

**Issue by 3ncanis** [Sinytra/Connector#941] opened 2024-03-26 17:26 UTC
### Minecraft version

1.20.1

### Describe the bug

When I'm using Zeta along with Sinytra Connector, I get a massive log spam of "Creative Tab Loop Found" and 1 or 2 of my creative tabs are completely deleted (usually the redstone tab or functional blocks tab) along with the items inside of them. They are also deleted from JEI, however are still able to be crafted. This doesn't happen when I'm just using Zeta without having Sinytra connector installed.

### Steps to reproduce

1. Install Zeta
2. Install Sinytra Connector/Forgified Fabric API
3. Create new world

### Logs

https://mclo.gs/YjJb3Vq

### Additional context

Another thing is that it seems to be extremely inconsistent, as in creating a new world doesn't always result in creative tabs being deleted.

**Comment by Su5eD** [comment] 2024-04-11 21:52
This seems to have been fixed in Zeta

**Closed by Su5eD** 2024-04-11 21:52 UTC
Labels: compat, forge compat

**Comment by 3ncanis** [comment] 2024-04-12 00:23
Unfortunately not yet, https://github.com/VazkiiMods/Quark/issues/4764#issuecomment-2050309152

**Comment by mateus3c** [comment] 2024-12-25 04:05
I can confirm this is still a problem

**Comment by mateus3c** [comment] 2024-12-25 04:08
also it looks like this issue doesn't occur if you're running forge  47.1.3
