### ISSUE TITLE
Hybrid Aquatic Crash even with Sinytra Connector and Forgified Fabric API

### ISSUE THREAD

**Issue by whatebbs** [Sinytra/Connector#1241] opened 2024-07-17 21:44 UTC
### Mod Name

Hybrid Aquatic

### Mod Homepage

https://modrinth.com/mod/hybrid-aquatic

### Minecraft version

1.20.1

### Describe the bug

When the 3 mods are installed, the game crashes when I click Single Player. I made a completely new installation so absolutely all mods in the folder are up to date.

### Steps to reproduce

1.Install Hybrid Aquatic, Forgified API and Sinytra Connector
2.Boot up Minecraft
3.Click Single-player
4. CRASH w log report

### Logs

https://pastebin.com/EJJwSMbC

### Additional context

Granted, I do have other mods including aquatic-based ones and several library mods, but I don't which ones are causing the conflict or if it's something else.

**Comment by whatebbs** [comment] 2024-07-17 22:15
After some further testing, the culprit may not be Hybrid Aquatic but the Sinystra itself.

**Comment by Su5eD** [comment] 2024-07-17 23:14
Duplicate of #1174

**Closed by Su5eD** 2024-07-17 23:14 UTC
Labels: compat
