### ISSUE TITLE
Incompatible with AdventureZ

### ISSUE THREAD

**Issue by Staticlp** [Sinytra/Connector#327] opened 2023-09-26 12:04 UTC
### Mod Name

AdventureZ

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/adventurez

### Describe the bug

Game crashes when entering the world

### Steps to reproduce

1.Install adventurez-1.4.19.jar and cloth-config-11.1.106-fabric
2.Entering a world
3.Game crashes
...

### Logs

below

### Additional context

[crash-2023-09-26_20.03.01-server.txt](https://github.com/Sinytra/Connector/files/12727246/crash-2023-09-26_20.03.01-server.txt)
[latest.log](https://github.com/Sinytra/Connector/files/12727247/latest.log)

**Comment by Lolothepro** [comment] 2023-09-26 12:07
Duplicate of https://github.com/Sinytra/Connector/issues/16

**Closed** 2023-09-26 12:19 UTC
Labels: compat
