### ISSUE TITLE
Crash with Iris/Sodium

### ISSUE THREAD

**Issue by Gamemassa** [Sinytra/Connector#178] opened 2023-09-04 13:48 UTC
### Mod Name

Iris/Sodium

### Mod Homepage

https://modrinth.com/mod/iris

https://modrinth.com/mod/sodium

### Describe the bug

The game fails to load and returns an error message.

### Logs

https://gist.github.com/Gamemassa/179ad549c686119a50cd239ec8685034

**Comment by kakashi1464** [comment] 2023-09-04 13:53
![image](https://github.com/Sinytra/Connector/assets/126709049/f8f2fa6f-9317-4523-aa27-fa315b796fa0)
![image](https://github.com/Sinytra/Connector/assets/126709049/b469eed1-60ec-4015-9584-71e39ac82a2c)

**Comment by Su5eD** [comment] 2023-09-04 13:53
Duplicate of #71

**Closed by Su5eD** 2023-09-04 13:53 UTC
Labels: compat
