### ISSUE TITLE
incompatibility with ledger

### ISSUE THREAD

**Issue by xiaopiEmma1221** [Sinytra/Connector#1488] opened 2024-10-21 20:44 UTC
### Mod Name

Ledger

### Mod Homepage

https://modrinth.com/mod/ledger

### Minecraft version

1.21.1

### Describe the bug

incompatibility

### Steps to reproduce

1.use Neoforge 21.1.72
2.run server
3.crash

### Logs

https://gist.github.com/xiaopiEmma1221/2c96e106100834ec7a0b8bab8369dc49#file-gistfile1-txt

**Comment by Su5eD** [comment] 2024-10-22 14:28
Duplicate of #215

**Closed as not planned by Su5eD** 2024-10-22 14:28 UTC
Labels: duplicate
