### ISSUE TITLE
Not compatible with Arclight server jar 

### ISSUE THREAD

**Issue by Thspooks** [Sinytra/Connector#600] opened 2023-12-12 15:17 UTC
### Mod Name

Arclight 

### Mod Homepage

https://github.com/IzzelAliz/Arclight

### Describe the bug

Crash upon startup

### Steps to reproduce

1. Install arclight on your  serrver for 1.20.1
2. Install Connector, Connector extras and FFAPI
3. crash
...

### Logs

https://pastebin.com/J5wUSpjR

### Additional context

I reported it to the arclight github, but im hoping you can resolve that :> ill provide more info if i missed something
https://pastebin.com/MLfY0eKb including modlist, just in case

**Comment by Su5eD** [comment] 2023-12-12 15:26
Duplicate of #205

**Comment by Thspooks** [comment] 2023-12-12 15:26
Didnt noticed! Sorry!

**Closed by Su5eD** 2023-12-12 15:26 UTC
Labels: compat
