### ISSUE TITLE
ReplayMod replay replaces modded blocks with other blocks.

### ISSUE THREAD

**Issue by axtrough** [Sinytra/Connector#1538] opened 2024-11-14 12:40 UTC
### Mod Name

ReplayMod

### Mod Homepage

https://modrinth.com/mod/replaymod

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Modded blocks get replaced with modded blocks from other mods. possibly fabric mods. but honestly no idea

### Steps to reproduce

1. Download replay mod with connector
2. download a mod like another furniture or farmers delight.
3. record in a single player server with some of the modded blocks placed down.

Then you should see that for example a chair has become a lantern.

### Logs

not needed

**Comment by kakashi1464** [comment] 2024-11-14 12:43
Probably a duplicate of #833 
Also, use ReforgedPlay instead of ReplayMod

**Comment by axtrough** [comment] 2024-11-14 12:45
I am trying to use the replay voice chat compat mod. And I cannot find a
version that works.

**Closed as not planned** 2024-11-19 17:13 UTC
Labels: duplicate
