### ISSUE TITLE
Crashing when trying to create world with Tectonic (NeoForge 1.21.1)

### ISSUE THREAD

**Issue by 3ncanis** [Sinytra/Connector#1401] opened 2024-09-10 09:43 UTC
### Mod Name

Tectonic

### Mod Homepage

https://modrinth.com/datapack/tectonic

### Minecraft version

1.21.1

### Describe the bug

When you try to create a new world with Sinytra Connector, Forgified Fabric API and Tectonic, you CTD

### Steps to reproduce

1. Install Sinytra/FFAPI
2. Install Tectonic
3. Try to create new world

### Logs

https://mclo.gs/pgYv2a8

**Comment by Su5eD** [comment] 2024-09-11 20:00
Duplicate of #1345

**Closed as not planned by Su5eD** 2024-09-11 20:00 UTC
Labels: duplicate
