### ISSUE TITLE
[1.20.1] Hephaestus Error on Connector Beta 19: Cannot invoke "java.nio.file.Path.toString()"

### ISSUE THREAD

**Issue by HaizUber** [Sinytra/Connector#388] opened 2023-10-17 17:16 UTC
### Mod Name

Hephaestus

### Mod Homepage

https://modrinth.com/mod/hephaestus

### Describe the bug

Failure message: [Connector] Error transforming jar C:\Users\GabzMejia\AppData\Roaming\PollyMC\instances\1.20.1\.minecraft\mods\.connector\temp\create-fabric-0.5.1-d-build.9+mc1.20.1$base-2.1.1148+1.20-entity-refactor$porting_lib_mixin_extensions-2.1.1148+1.20-entity-refactor.jar 		java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null

### Steps to reproduce

1.Install Connector Beta 19, Hephaestus 1.20.1-3.6.3.232, Create Fabric DM-Earth Edition v0.5.1.d Patch 2 together
2.Crash on startup
3.
...

### Logs

https://gist.github.com/HaizUber/18148bd9e594b3afa4c232478081e4ce

### Additional context

Was Trying Create Fabric DM-Earth Edition and Hephaestus Together since it claimed compatibility between the two mods. Kinda expected it wouldn't work with Connector but I gave it a shot, crashes with failure message: [Connector] Error transforming jar C:\Users\GabzMejia\AppData\Roaming\PollyMC\instances\1.20.1\.minecraft\mods\.connector\temp\create-fabric-0.5.1-d-build.9+mc1.20.1$base-2.1.1148+1.20-entity-refactor$porting_lib_mixin_extensions-2.1.1148+1.20-entity-refactor.jar 		java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null

**Comment by Su5eD** [comment] 2023-10-17 17:19
Duplicate of #74

**Closed by Su5eD** 2023-10-17 17:19 UTC
Labels: compat
