### ISSUE TITLE
Crahs on startup with OptiFine

### ISSUE THREAD

**Issue by VanillaCold** [Sinytra/Connector#530] opened 2023-11-24 16:04 UTC
### Describe the bug

When OptiFine is installed, the game will crash on startup consistently.

### Steps to reproduce

1. Install OptiFine (with or without OptiFabric)
2. Launch Minecraft
3. The game will crash.

### Logs

https://pastebin.com/FFKBFPJt

### Additional context

I can't use Sodium or anything like it, due to the sheer quantity of mods that'd be required for the functionality needed combined with how, if I recall correctly, Forge takes longer to start up when more mods are installed.  
I have tried this with and without other mods installed; the game consistently crashes regardless.

(In the crash log, my Windows username was replaced with {REDACTED}, as I do not want to share it publically.)

**Comment by kakashi1464** [comment] 2023-11-24 16:07
Optifine is incompatible with forgified fabric api

**Comment by kakashi1464** [comment] 2023-11-24 16:08
the problem cannot be solved because optifine is a closed source mod

**Comment by DoritosSpR** [comment] 2023-11-24 16:09
use embeddium instead

**Comment by Su5eD** [comment] 2023-11-24 16:09
Duplicate of #111

**Closed by Su5eD** 2023-11-24 16:09 UTC
Labels: bug

**Comment by VanillaCold** [comment] 2023-11-24 16:11
> Duplicate of #111

ah, sorry. I couldn't find that when I made my post.



> use embeddium instead

I don't actually care about performance gains tbh, I'm moreso wanting the other functionality provided. I'll probably just try to find an alternative though.

**Comment by kakashi1464** [comment] 2023-11-24 16:23
> > Duplicate of #111
> 
> ah, sorry. I couldn't find that when I made my post.
> 
> > use embeddium instead
> 
> I don't actually care about performance gains tbh, I'm moreso wanting the other functionality provided. I'll probably just try to find an alternative though.
[mods.txt](https://github.com/Sinytra/Connector/files/13460946/mods.txt)
I dropped a list of mods that will help you replace Optifine
