### ISSUE TITLE
When I put in CreativeCore_FORGE, it won't start.

### ISSUE THREAD

**Issue by Goheimochin** [Sinytra/Connector#194] opened 2023-09-05 12:06 UTC
### Mod Name

CreativeCore_FORGE

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/creativecore

### Describe the bug

When I put in CreativeCore_FORGE, it won't start.

### Steps to reproduce

1.Connector-1.0.0-beta.11+1.20.1-full
2.fabric-api-0.87.0+1.9.8+1.20.1
3.CreativeCore_FORGE_v2.10.34_mc1.20.1
...

### Logs

-1

**Comment by Su5eD** [comment] 2023-09-05 12:07
Duplicate of #122, the fix will be available in the upcoming release

**Closed by Su5eD** 2023-09-05 12:07 UTC
Labels: compat

**Comment by Goheimochin** [comment] 2023-09-05 20:06
This release has been successfully activated!
Thank you.
