### ISSUE TITLE
[1.20.1] Crash with clientcommands

### ISSUE THREAD

**Issue by t3201** [Sinytra/Connector#1176] opened 2024-06-21 05:07 UTC
### Mod Name

clientcommands

### Mod Homepage

https://github.com/Earthcomputer/clientcommands

### Minecraft version

1.20.1

### Describe the bug

Crashes early at startup

### Steps to reproduce

Installing NeoForge 47.1.106, clientcommands-2.8.5, Forged Fabric API 0.92.2-1.11.8, and Connector 1.0.0 (beta.43) results in the game crashing during the mod loading process.

### Logs

https://gist.github.com/t3201/03762edaf66957a5874c069c6bd6f35a

### Additional context

The java.lang.RuntimeException: java.lang.reflect.InvocationTargetException typically indicates that when a method is called via reflection, an exception was thrown by the target method.

**Comment by Su5eD** [comment] 2024-06-21 06:40
Duplicate of #441

**Closed by Su5eD** 2024-06-21 06:40 UTC
Labels: compat
