### ISSUE TITLE
Possible geckolib cross-platform incompatability with Critters and Companions

### ISSUE THREAD

**Issue by jg2002-j** [Sinytra/Connector#1151] opened 2024-06-12 13:17 UTC
### Mod Name

crittersandcompanions-1.20.1-2.1.6.jar

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/critters-and-companions

### Minecraft version

1.20.1

### Describe the bug

Minecraft crashes with 

### Steps to reproduce

Mods installed:
- **crittersandcompanions-1.20.1-2.1.6.jar**
- Connector-1.0.0-beta.43+1.20.1.jar
- ConnectorExtras-1.10.1+1.20.1.jar
- geckolib-fabric-1.20.1-4.4.6.jar
- soulslike-weaponry-1.1.3-1.20-fabric.jar
- Others, but those are the relevant ones I think

Error: ```Caused by: java.lang.IllegalStateException: Missing layer definitions: [soulsweapons:nights_edge#main, soulsweapons:big_chungus#main, soulsweapons:swordspear_entity#main]```

### Logs

https://mclo.gs/XnzzvFU

### Additional context

Related to [Issue #231](https://github.com/Sinytra/Connector/issues/231)

**Comment by RoomAlex68** [comment] 2024-06-12 13:57
#231

**Comment by Su5eD** [comment] 2024-06-12 18:55
Duplicate of #231

**Closed by Su5eD** 2024-06-12 18:55 UTC
Labels: compat
