### ISSUE TITLE
Hephaestus crash on beta.35

### ISSUE THREAD

**Issue by Mikka6489** [Sinytra/Connector#788] opened 2024-01-28 04:37 UTC
### Mod Name

Hephaestus

### Mod Homepage

https://modrinth.com/mod/hephaestus

### Minecraft version

1.20.1

### Describe the bug

When loading with Hephaestus on connecter beta.35, minecraft loads but brings up a new crash screen compared to previous versions of connecter, where it would just crash before loading the game

### Steps to reproduce

1. Load Minecraft with Hephaestus 3.6.3.241, Forgified Fabric Api 0.91.0+1.10.8 and Connector-1.0.0-beta.35
2. Crash appears in the "Error loading mods" screen

### Logs

https://gist.github.com/Mikka6489/dda5410ba4890dc717e5a2b411b81456

### Additional context

The crash screen shows the error:
[Connector] Error transforming jar /home/mikka/.local/share/multimc/instances/1.20.4/.minecraft/mods/.connector/temp/Hephaestus-1.20.1-3.6.3.241$Porting-Lib-2.1.1141+1.20-entity-refactor$porting_lib_base-2.1.1141+1.20-entity-refactor.jar
		java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to execute task io/github/fabricators_of_create/porting_lib/mixin/common/LevelMixin.class

**Comment by Su5eD** [comment] 2024-01-28 08:57
Duplicate of #74

**Closed** 2024-01-28 08:57 UTC
Labels: compat
