### ISSUE TITLE
Valkyrien Skies Forge/Fabric crash

### ISSUE THREAD

**Issue by FullMetalMaster** [Sinytra/Connector#1042] opened 2024-04-26 23:10 UTC
### Mod Name

Valkyrien Skies

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies

### Minecraft version

1.20.1

### Describe the bug

exit Code Zero crash on Startup

### Steps to reproduce

1. have Immersive Portals, MiniScaled, and Valkyrien Skies Forge or Fabric
2. on load if forge you get exit code 0 and if fabric the connect your mod fails to transform the skies mod
using forge 47.1.3

### Logs

https://pastebin.com/rgDpCee7

### Additional context

tryed with both mods I wanted to use inverse of portals and Forge in order to make goofy things happen with Clockwork unfortunately immersive portals and Clockwork how to fix compatibility with each other as well I just also noticed these two mods in the Forge environment also are not compatible but they are in fabric

**Comment by Su5eD** [comment] 2024-04-27 06:54
Duplicate of #938

**Closed by Su5eD** 2024-04-27 06:54 UTC
Labels: compat
