### ISSUE TITLE
Iron's Spells 'n Spellbooks crashed with fabric geckolib while wearing its armor

### ISSUE THREAD

**Issue by liangmoe** [Sinytra/Connector#859] opened 2024-02-25 15:18 UTC
### Mod Name

Iron's Spells 'n Spellbooks

### Mod Homepage

https://modrinth.com/mod/irons-spells-n-spellbooks

### Minecraft version

1.20.1

### Describe the bug

issue only occured with fabric geckolib

### Steps to reproduce

1.use fabric geckolib
2.wear a armor from Iron's Spells 'n Spellbooks
3.crash
...

### Logs

latest: https://mclo.gs/nhdd1Nv

**Comment by liangmoe** [comment] 2024-02-25 15:21
umm crash report: https://mclo.gs/XAm30Zt
https://github.com/Sinytra/Connector/assets/135343248/b12b615d-37cc-4561-a7a7-72f71f25192e

**Comment by Su5eD** [comment] 2024-02-25 18:44
Duplicate of #231. You'll need to use the Forge version of geckolib with Forge mods for the time being.

**Closed by Su5eD** 2024-02-25 18:44 UTC
Labels: compat
