### ISSUE TITLE
[1.20.1] Forge mod - Oculus

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#109] opened 2023-08-25 01:38 UTC
### Mod Name

Oculus

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/oculus

### Describe the bug

Cannot start the game.

### Steps to reproduce

1. Install Oculus and Rubidium.
2. Run with Sinytra.
3. Poopfart

### Logs

https://gist.github.com/Cixon/4f0fe5d91c7f0805ca1de9369fa765a5

### Additional context

Hi I really like how plugNplay sinytra is so far, I think you're doing a amazing job dev and I hope everything is going well.

I'd really love to see a fix to this or perhaps a separate mod that caters to sinytra's environment so we can have shaders soon, thanks!

_Tested only those 4 mods on fml 47.1.3._

**Comment by Lolothepro** [comment] 2023-08-25 10:05
Duplicate of https://github.com/Sinytra/Connector/issues/39

**Comment by SpatialParadox** [comment] 2023-08-25 10:40
The latest version of Oculus isn't compatible with Rubidium 0.7.0a; see Asek3/Oculus#430

**Comment by Su5eD** [comment] 2023-08-25 21:56
As stated in the linked issue #39, Rubidium 0.6.5 is not compatible with Connector. The best I can recommend is wait until Oculus is updated for Rubidium 0.7.x. Both mods should run fine after that.

**Closed by Su5eD** 2023-08-25 21:56 UTC
Labels: compat
