### ISSUE TITLE
Spectrum 1.7.11 broken on Sinytra beta 43

### ISSUE THREAD

**Issue by Red6785** [Sinytra/Connector#1094] opened 2024-05-18 05:52 UTC
### Mod Name

Spectrum 1.7.11

### Mod Homepage

https://modrinth.com/mod/spectrum

### Minecraft version

1.20.1

### Describe the bug

The game does not boot.

### Logs

https://mclo.gs/huugkOx

### Additional context

Before adding in any of the dependencies, the game does not crash while loading, however the game is unplayable because the mod is missing dependencies. Post adding dependencies, it crashes and requests the addition of Cardinal Components API. Post adding that, it crashes again with no obvious solution.

**Comment by Su5eD** [comment] 2024-05-18 08:44
Duplicate of #1060

**Closed by Su5eD** 2024-05-18 08:44 UTC
Labels: compat
