### ISSUE TITLE
Apotheosis (Forge) crashing when installed with AdventureZ (Fabric)

### ISSUE THREAD

**Issue by SlayDigger** [Sinytra/Connector#610] opened 2023-12-15 00:51 UTC
### Mod Name

Apotheosis, AdventureZ

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/apotheosis, https://www.curseforge.com/minecraft/mc-mods/adventurez

### Describe the bug

If both Apotheosis & AdventureZ are installed at the same time alongside Connector & Connector Extras, the game crashed on startup. 

### Steps to reproduce

1. Install Connector, Forgified Fabric API, Architectury API, & Connector Extras
2. Install Apotheosis, Apothic Attributes, Patchouli & Placebo
3. Install AdventureZ & Cloth Config
4. Attempt to startup game.

### Logs

https://gist.github.com/SlayDigger/c7583969851dad671a4fd6b26a3b37a2

### Additional context

I'm not gonna lie I completely forgot about trying to resolve which mod was incompatible. I found out that the problem only occurred if AdventureZ and Apotheosis were both installed at the same time.

**Comment by itzinxta** [comment] 2023-12-15 02:50
this is not connectors fault, it's a mod incompat. in a situation like this, it's one or the other mod.

**Comment by itzinxta** [comment] 2023-12-15 02:52
you could ask Apotheosis or AdventureZ to fix this issue since it's on their end.

**Comment by Su5eD** [comment] 2023-12-15 21:06
Duplicate of #526

**Closed by Su5eD** 2023-12-15 21:06 UTC
Labels: compat
