### ISSUE TITLE
Gravity Mod Incompatibility

### ISSUE THREAD

**Issue by EpicGageMAGEmc** [Sinytra/Connector#1072] opened 2024-05-08 19:50 UTC
### Mod Name

Amethyst Gravity: Reattracted, and Gravity Changer (quoteall fork)

### Mod Homepage

https://modrinth.com/mod/gravity-api-fork, https://modrinth.com/mod/amethyst-gravity-reattracted

### Minecraft version

1.20.1

### Describe the bug

The game crashes on startup when only using these mods and the dependencies.

### Steps to reproduce

1. Install the mods
2. Launch the game
3. Crash

### Logs

https://mclo.gs/HpX1hQQ

**Comment by EpicGageMAGEmc** [comment] 2024-05-08 19:56
for reference, the exact same mods, exact same versions work fine on fabric

**Comment by Liamgrayskull** [comment] 2024-05-08 23:00
Can replicate this, although I think it's a duplicate

**Comment by Su5eD** [comment] 2024-05-09 11:45
Duplicate of #135

**Closed by Su5eD** 2024-05-09 11:45 UTC
Labels: compat
