### ISSUE TITLE
Immersive Portals causing server to crash on startup.

### ISSUE THREAD

**Issue by LePizzaRabbit** [Sinytra/Connector#921] opened 2024-03-21 01:33 UTC
### Mod Name

Immersive Portals

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod

### Minecraft version

1.20.1

### Describe the bug

Crashes on startup with immersive portals (Serverside)

### Steps to reproduce

1. Find a server host/Server panel
2. Install the fabric/forge api, install Connectors, and Immersive Portals
3. Start
4. Watch it crash and wonder where it all went wrong

### Logs

https://gist.github.com/LePizzaRabbit/82abdfef3c987c04bad30bd63d9a5c41

**Comment by Su5eD** [comment] 2024-03-21 20:56
Duplicate of #904, will be fixed in the next release

**Closed by Su5eD** 2024-03-21 20:56 UTC
Labels: compat
