### ISSUE TITLE
not working with fabric-language-kotlin

### ISSUE THREAD

**Issue by FullMetalMaster** [Sinytra/Connector#486] opened 2023-11-07 04:44 UTC
### Mod Name

kotlin

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin

### Describe the bug

exit Code Zero crash on Startup

### Steps to reproduce

1. load with Connector, fabric-language-kotlin mod and cobblemon

[latest.log](https://github.com/Sinytra/Connector/files/13275794/latest.log)

### Logs

uploaded logs

**Comment by Linguardium** [comment] 2023-11-07 04:53
Have you tried reducing the mods to only those 3 and their dependencies to make sure it is specifically those that are incompatible and not some additional mod? It is important to create the smallest mod set that can reproduce your problem

**Comment by Linguardium** [comment] 2023-11-07 04:53
Also appears to be a duplicate of #482

**Closed** 2023-11-07 06:52 UTC
Labels: compat
