### ISSUE TITLE
Potential Geckolib Issue

### ISSUE THREAD

**Issue by KorytheMaril** [Sinytra/Connector#351] opened 2023-10-03 14:09 UTC
### Mod Name

Geckolib/Marium's Soulslike Weaponry

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry

### Describe the bug

It would seem that using the Fabric version of Geckolib causes certain objects from other mods not to load in correctly, appearing completely transparent. If using the Forge version of Geckolib, the Marium's mod crashes due to not recognizing the Forge Geckolib. Attempting to load both Forge and Fabric Geckolib also crashes the game.

### Steps to reproduce

1. Download Marium's Soulslike Weaponry and the Fabric version of Geckolib (since the mod doesn't recognize the Forge version of Geckolib, even though, bizarrely, Forge mods that depend on Geckolib will recognize the Fabric version).
2. Download something like L_Ender's Cataclysm
3. Boot up game, go to creative, check inventory, notice some items show up as transparent.
...

### Logs

N/A

### Additional context

I do think the issue lies in how the Connector handles loading Fabric Geckolib, since mods that require Forge's Geckolib don't cause this issue when the Connector and Connector Extras are included.

Modpack was custom made, and several tests were conducted to see when issues would pop up. Only when running Marium's Soulslike Weaponry and Fabric Geckolib did any issues come up (and to get Marium's Soulslike Weaponry to load, you have to include Fabric Geckolib).

**Comment by Su5eD** [comment] 2023-10-03 14:16
Duplicate of #231

**Closed by Su5eD** 2023-10-03 14:16 UTC
Labels: compat
