### ISSUE TITLE
sodium incompatibility (I think)

### ISSUE THREAD

**Issue by angelaix** [Sinytra/Connector#1184] opened 2024-06-24 04:54 UTC
### Mod Name

sodium

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sodium

### Minecraft version

1.20.1

### Describe the bug

the launcher dont function at the moment of lauch it crashes

### Steps to reproduce

1.down load mods 
Connector-1.0.0-beta.44+1.20.1
ConnectorExtras-1.11.1+1.20.1
dynamiclightsreforged-1.20.1_v1.6.0
fabric-api-0.92.2+1.11.8+1.20.1
forge-1.20.1-47.2.0-installer
indium-1.0.32+mc1.20.1
journeymap-1.20.1-5.10.0-forge
MouseTweaks-forge-mc1.20-2.25
reeses_sodium_options-1.7.2+mc1.20.1-build.101
sodium-extra-0.5.4+mc1.20.1-build.115
sodium-fabric-0.5.10+mc1.20.1
Xaeros_Minimap_23.9.7_Forge_1.20

2. launch minecraft in 1.20.1

### Logs

https://gist.github.com/angelaix/f1c183624b3026a7062049d7dcfd339d

**Comment by Su5eD** [comment] 2024-06-24 06:53
Duplicate of #71

**Closed by Su5eD** 2024-06-24 06:53 UTC
Labels: compat
