### ISSUE TITLE
disappeared background music(Caused by only two mods[Sinytra Connector, Forgified Fabric API])

### ISSUE THREAD

**Issue by X-Machiavelli** [Sinytra/Connector#1409] opened 2024-09-13 03:40 UTC
### Minecraft version

1.21

### Describe the bug

After installing 'Sinytra Connector' & 'Forgified Fabric API' mod, Minecraft no longer plays background music (or CD music inserted in the jukebox).

### Steps to reproduce

1. neoforge 21.0.167 (minecraft version 1.21)
2. forgified-fabric-api-0.101.2+2.0.10+1.21.jar
3. connector-2.0.0-beta.1+1.21-full.jar
...
Background music doesn't play, but block installation and entity sounds work fine.

**Comment by Inonedn** [comment] 2024-09-15 18:24
I'm having this issue too

**Comment by ZervisM** [comment] 2024-09-17 07:55
same here

**Comment by Fattyton** [comment] 2024-09-18 03:57
me 2

**Comment by EugeneLeclerc** [comment] 2024-09-21 14:44
Same here.

**Comment by Su5eD** [comment] 2024-09-22 15:54
Does this occur with only FFAPI installed? Possible duplicate of https://github.com/Sinytra/ForgifiedFabricAPI/issues/150

**Comment by ratzit0213** [comment] 2024-09-25 09:07
> Does this occur with only FFAPI installed? Possible duplicate of [Sinytra/ForgifiedFabricAPI#150](https://github.com/Sinytra/ForgifiedFabricAPI/issues/150)

This occurs for my instance in 1.21.1. I've tried multiple versions of Neoforge with all versions of FFAPI. I also tried moving the install folder to a different drive as well as 1.21 with Neoforge 21.0.16. All resulted in the background music and the disc music not playing any sound.

**Comment by Su5eD** [comment] 2024-09-25 13:16
I understand that it occurs in your instance, but do you have anything else installed besides FFAPI, namely, Connector?

**Comment by Tapacywka** [comment] 2024-09-25 13:29
> I understand that it occurs in your instance, but do you have anything else installed besides FFAPI, namely, Connector?

Here are the logs I just made: https://mclo.gs/WCacVva
A clean instance of NeoForge 21.1.61 with Connector and Forgified Fabric API.
No music in the main menu, no background music while playing in the open world, no music from records.

And these are logs with Forgified Fabric API only (without Connector): https://mclo.gs/oVBZqAv
Still the same error, no music anywhere in the above tests.

Finally, one last test with Connector only (no FFAPI): https://mclo.gs/wUT6vkr
Music finally appeared.

**Comment by Tapacywka** [comment] 2024-09-25 13:30
Thus, this error is related to FFAPI and not Connector.

**Comment by ratzit0213** [comment] 2024-09-25 13:36
> I understand that it occurs in your instance, but do you have anything else installed besides FFAPI, namely, Connector?

Just FFAPI.

**Comment by BrandonPotter0** [comment] 2024-09-26 00:58
I can also confirm that Forgified Fabric API is causing music to not play. It seems that it does play, we just cant hear it. I use the mod with Crowd Control.

**Comment by Su5eD** [comment] 2024-09-28 11:24
Duplicate of https://github.com/Sinytra/ForgifiedFabricAPI/issues/150

**Closed as not planned by Su5eD** 2024-09-28 11:24 UTC
Labels: bug, duplicate, 1.21.x, behavior
