### ISSUE TITLE
Update Mod = crash server

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#424] opened 2023-10-23 14:17 UTC
### Describe the bug

I'm update Connector - and now my server is down at all

### Steps to reproduce

Idk

I tried many versions and it was in vain to delete the one I had, because now I don't know what it was originally

### Logs

https://mclo.gs/iqL35hm

**Comment by Su5eD** [comment] 2023-10-23 14:21
> java.lang.RuntimeException: Timed out waiting for jar remap

Duplicate of #275

**Closed by Su5eD** 2023-10-23 14:21 UTC
Labels: bug
