### ISSUE TITLE
Replay mod incorrectly displays items in replay.

### ISSUE THREAD

**Issue by FoxJune** [Sinytra/Connector#501] opened 2023-11-11 14:49 UTC
### Mod Name

Replaymod

### Mod Homepage

https://www.replaymod.com/

### Describe the bug

Replaymod renders items incorrectly. They appear to be different items.

### Steps to reproduce

1. Enter your world.
2. Start replay recording.
3. Throw items from some Forge mod on the ground (I used scrolls and boots from Iron's Spells & Spellbooks).
4. Save replay recording.
5. Open replay recording and items will differ (In my case instead of scrolls and boots I got Create's blocks).

### Logs

https://pastebin.com/aPGScrJe

### Additional context

Here is the list of mods to reproduce this bug:

- caelus-forge-3.1.0+1.20.jar
- Connector-1.0.0-beta.23+1.20.1.jar
- create-1.20.1-0.5.1.f.jar
- curios-forge-5.4.2+1.20.1.jar
- fabric-api-0.90.7+1.9.30+1.20.1.jar
- geckolib-neoforge-1.20.1-4.2.4.jar
- irons_spellbooks-1.20.1-2.0.3.jar
- player-animation-lib-forge-1.0.2-rc1+1.20.jar
- replaymod-1.20.1-2.6.13.jar

I also tried geckolib-forge-1.20.1-4.2.4.jar instead of geckolib-neoforge-1.20.1-4.2.4.jar and the issue persists.

Note: I installed latest versions of Sinytra and Forgified API.

Video demonstration: https://www.youtube.com/watch?v=ImFeZ36BSPI

IDK if it will be helpful but I also provided log file.

**Comment by VladisCrafter** [comment] 2024-02-17 22:21
See #833, might be a similar issue!

**Comment by Su5eD** [comment] 2024-03-29 19:28
Duplicate of #833

**Closed by Su5eD** 2024-03-29 19:28 UTC
Labels: compat
