### ISSUE TITLE
Issue with Hybrid Aquatic & Geckolib (forge)

### ISSUE THREAD

**Issue by Dirt-Eater** [Sinytra/Connector#1242] opened 2024-07-17 23:39 UTC
### Mod Name

Hybrid Aquatic

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/hybrid-aquatic

### Minecraft version

1.20.1

### Describe the bug

If Hybrid aquatic is installed with both the fabric and forge versions of geckolib it crashes on startup, however there are other mods such as LUMINOUS that require both. If LUMINOUS is installed with only the fabric version of geckolib it crashes when looking through the inventory tab for the mod in creative. This crash does not happen when LUMINOUS is installed with both the forge and fabric versions of geckolib. Another mod this affects is what the gecko, which similarly requires both versions to function.

### Steps to reproduce

1. Download fabric api
2. Download forgified fabric api
3. Download sinytra connector
4. Download connector extras
5. Download fabric kotlin
6. Download kotlin for forge
7. Download geckolib (forge)
8. Download geckolib (fabric)
9. Download Hybrid aquatic 
10. Start game

### Logs

https://pastebin.com/tSA1uRDS

**Comment by Dirt-Eater** [comment] 2024-07-17 23:52
I can make another post detailing the crashes with LUMINOUS or what the gecko and include those crashlogs if it is helpful.

**Comment by Su5eD** [comment] 2024-07-22 20:57
Duplicate of #231

**Closed by Su5eD** 2024-07-22 20:57 UTC
Labels: compat
