### ISSUE TITLE
Replay Mod no work

### ISSUE THREAD

**Issue by Koolguys** [Sinytra/Connector#95] opened 2023-08-22 20:08 UTC
### Discussed in https://github.com/Sinytra/Connector/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **Su5eD** August  8, 2023</sup>
# Mod Compatibility

A maintained list of known mods and compatibility state in regards to Connector.

### Help us test!

We welcome any help. If you have tested or experienced issues with a mod and would like let us know, just comment on this post and we'll look into listing the mod. Thanks!

### Compatibility statuses

- ✅Compatible - This mods is tested and verified to be compatible with Connector
- ⚠️Functional - This mod loads with Connector, but might contain bugs
- ❌Incompatible - This mod is not compatible with Connector

# Status list

| 📦 Mod Name | 🔗 Link | ❓ Status | 🗒️ Notes |
|:------:|:------:|:------:|:------:|
| LambDynamicLights | [Modrinth](https://modrinth.com/mod/lambdynamiclights) | ✅ |  |
| Tech Reborn | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/techreborn) | ✅ |  |
| Terrestria | [Modrinth](https://modrinth.com/mod/terrestria) | ✅ |  |
| Traverse| [Modrinth](https://modrinth.com/mod/traverse) | ✅ |  |
| amecs api | [GitHub](https://github.com/Siphalor/amecs-api) | ❌ | Conflicting mixins with Forge's keybind API |
| Forge Config API Port | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric) | ❌ | Provides modified versions of Forge config classes | 
| Reach Entity Attributes | [GitHub](https://github.com/JamiesWhiteShirt/reach-entity-attributes) | ❌ | Conflicts with Forge attribute modifiers |
| Sodium | [Modrinth](https://modrinth.com/mod/sodium) | ❌ | Conflicts with Forge's Early Loading Screen |</div>

**Comment by Su5eD** [comment] 2023-08-22 20:33
Duplicate of #94 (also repost of mod compat thread? :thinkies:)

**Closed by Su5eD** 2023-08-22 20:33 UTC
