### ISSUE TITLE
[1.20.1] Carpet Mod Incompatibility with Sinytra Connector

### ISSUE THREAD

**Issue by samozoid** [Sinytra/Connector#1089] opened 2024-05-14 15:06 UTC
### Mod Name

Carpet Mod

### Mod Homepage

https://modrinth.com/mod/carpet

### Minecraft version

1.20.1

### Describe the bug

Carpet Crashes while forge is loading

### Steps to reproduce

1. Install Minecraft 1.20.1
2. Install Forge 47.1.30
3. Drag Carpet Mod, Connector, Connector Extras and FFAPI
4. Run Minecraft
...

### Logs

https://gist.github.com/samozoid/efd890432b18ba35e0905524530496cb

### Additional context

I am using Prism Launcher 8.3

**Comment by Su5eD** [comment] 2024-05-14 15:45
Duplicate of #296

**Closed by Su5eD** 2024-05-14 15:45 UTC
Labels: compat
