### ISSUE TITLE
(shaders) shadowcopm error 

### ISSUE THREAD

**Issue by kekis1234** [Sinytra/Connector#408] opened 2023-10-21 23:52 UTC
### Describe the bug

Light now working properly

### Steps to reproduce

Torches and other sources of light not having any light 

### Additional context

![изображение_2023-10-22_024914890](https://github.com/Sinytra/Connector/assets/148545221/feaea45f-69c1-4621-9d82-8784de795947)
![image](https://github.com/Sinytra/Connector/assets/148545221/1e2f7f35-5421-4767-abea-66522c387e52)
![image](https://github.com/Sinytra/Connector/assets/148545221/65e42e4b-4888-4c23-a9ac-918cc80c8290)

**Comment by Su5eD** [comment] 2023-10-22 07:32
Duplicate of #409

**Closed by Su5eD** 2023-10-22 07:32 UTC
Labels: bug
