### ISSUE TITLE
models don't load with connecter enabled

### ISSUE THREAD

**Issue by Thunderrock424242** [Sinytra/Connector#385] opened 2023-10-16 18:44 UTC
### Describe the bug

models don't load with connecter enabled

### Steps to reproduce

1. load my modpack
2.start game and models don't load
3.
...
 

### Additional context

[latest.log](https://github.com/Sinytra/Connector/files/12920677/latest.log)
logs are here

**Comment by rainysux** [comment] 2023-10-16 19:01
its Ducklib

**Comment by rainysux** [comment] 2023-10-16 19:02
https://www.curseforge.com/minecraft/mc-mods/duclib adds entity models and animations that are unlike java models

**Comment by Thunderrock424242** [comment] 2023-10-16 23:07
i don't have a mod called duclib

**Comment by rainysux** [comment] 2023-10-16 23:09
"Mixin config duclib.mixin.json does not specify "minVersion" property"

**Comment by Thunderrock424242** [comment] 2023-10-16 23:17
is that the issue tho?

**Comment by rainysux** [comment] 2023-10-16 23:19
its a guess, with the context of models not rendering and that being the first error, its just a hunch, however I am not 100% sure. You should do a debug log

**Comment by rainysux** [comment] 2023-10-16 23:23
theres also alot of supplementaries, moonlight in it, or doggy talents

**Comment by Thunderrock424242** [comment] 2023-10-17 00:31
i have been using them before and no problom happens its only when i enable this mod

**Comment by rainysux** [comment] 2023-10-17 00:35
it'd be helpful for the dev to know which mod is causing the issue. All these mods I have said are guesses so you can determine which one is the one conflicting it. Which is why you should do your part in trying get it to solved.

**Comment by Thunderrock424242** [comment] 2023-10-17 01:58
It started happening after this update

**Comment by Thunderrock424242** [comment] 2023-10-17 01:59
The new update

**Comment by Su5eD** [comment] 2023-10-21 15:07
Which mods exactly are required to reproduce this issue?

**Comment by Thunderrock424242** [comment] 2023-10-21 16:02
so i am using a big modpack so i will just send you the link to the file since i can't send it here casue its big

**Comment by Thunderrock424242** [comment] 2023-10-21 16:06
https://legacy.curseforge.com/minecraft/modpacks/wilderness-odyssey/files/4809326 this is it

**Comment by Thunderrock424242** [comment] 2023-10-21 16:18
That link may not work give me a sec

**Comment by Su5eD** [comment] 2023-10-21 17:28
Please use binary search or otherwise track down the exact mod(s) causing the issue

**Comment by Su5eD** [comment] 2023-10-27 19:45
Closing as cannot reproduce

**Closed by Su5eD** 2023-10-27 19:45 UTC
Labels: needs info
