### ISSUE TITLE
Crashes on init with ExtraSounds and Promenade

### ISSUE THREAD

**Issue by enzogfaria** [Sinytra/Connector#390] opened 2023-10-18 23:27 UTC
### Describe the bug

The game crashes when the mods ExtraSounds and Promenade are together

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/9U22RxzL

### Additional context

when together in the fabric it starts normally. in forge with connector crashes

**Comment by Su5eD** [comment] 2023-10-19 05:17
Try installing connector extras

**Comment by enzogfaria** [comment] 2023-10-19 08:56
I have the latest version, is not working

**Comment by Su5eD** [comment] 2023-10-19 17:21
Do these two mods alone cause a crash? I've tested them myself and everything appears to work fine on the current dev build. Also, you crash log mentions the error comes from "Biome makeover", which is neither of the two mods mentioned

**Comment by RoomAlex68** [comment] 2023-10-25 05:08
Crashed with connecter beta 21 for both

**Comment by RoomAlex68** [comment] 2023-10-26 02:56
Okay Promenade works because I need Fabric Terrablender but am not sure extra sounds

**Comment by Su5eD** [comment] 2023-10-31 10:17
Closing as cannot reproduce / not enough information provided. Confirmed to work on beta 22

**Closed by Su5eD** 2023-10-31 10:17 UTC
Labels: needs info
