### ISSUE TITLE
Beta 30 breaks OwO Lib

### ISSUE THREAD

**Issue by mateus3c** [Sinytra/Connector#625] opened 2023-12-18 12:56 UTC
### Describe the bug

OwO Lib won't load with Connector beta 30, it loads with beta 29 tho. I have attached the logs on "additional context"

### Steps to reproduce

1. Add OwO Lib
2. Try to load the game

### Additional context

![image](https://github.com/Sinytra/Connector/assets/122059128/bc347e47-7a8f-4d4b-a0d1-89245852259b)
[latest.log](https://github.com/Sinytra/Connector/files/13703971/latest.log)
[latest_console.log](https://github.com/Sinytra/Connector/files/13703974/latest_console.log)

**Comment by Su5eD** [comment] 2023-12-18 13:26
Duplicate of #620

**Closed as not planned by Su5eD** 2023-12-18 13:26 UTC
Labels: duplicate
