### ISSUE TITLE
Loading the sheets class too early

### ISSUE THREAD

**Issue by abby-cadabra** [Sinytra/Connector#1161] opened 2024-06-15 12:33 UTC
### Mod Name

Bountiful Fares 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bountiful-fares

### Minecraft version

1.20.1

### Describe the bug

Crashes when running with Supplementaries due to "loading the sheets class too early." 

### Steps to reproduce

1. In the Forge environment, run any version of Supplementaries past 2.8.10
2. Run any version of Bountiful Fares through Sinytra
3. Crash on launch

Bountiful Fares is a fabric-only mod that, by itself, runs beautifully in the Forge environment through Sinytra. But when running alongside the newer versions of Supplementaries, it causes Supplementaries to return a crash: "Some OTHER mod loaded the Sheets class to early, causing modded banner patterns and sherds textures to not include modded ones." Testing reveals the "OTHER mod" to be Bountiful Fares.

This crash has been reported to Bountiful Fares, who puts it down to an error with Sinytra and doesn't intend to action it: https://github.com/Heccology/Bountiful-Fares/issues/18 (you can also see the relevant crash log and latest log on this page).

Hoping this can be fixed on the Sinytra end somehow. 

### Logs

[22:05:38] [Server thread/ERROR]: Encountered an unexpected exception net.mehvahdjukaar.supplementaries.common.utils.VibeChecker$BadModError: Some OTHER mod loaded the Sheets class to early, causing modded banner patterns and sherds textures to not include modded ones. Refusing to proceed further. Do Not report this to Supplementaries

**Comment by Su5eD** [comment] 2024-06-15 12:50
Possible duplicate of #1090

**Comment by Su5eD** [comment] 2024-06-15 12:50
Try using the latest dev build

**Comment by abby-cadabra** [comment] 2024-06-16 06:05
Cheers, the dev version seems to fix it nicely. Thank you!

**Closed** 2024-06-16 06:57 UTC
Labels: compat
