### ISSUE TITLE
Replay mod viewer is showing different models 

### ISSUE THREAD

**Issue by jimmytimmy65** [Sinytra/Connector#1124] opened 2024-06-03 07:10 UTC
### Minecraft version

1.20.1

### Describe the bug

Replay mod viewer is showing different models 

### Steps to reproduce

1. Record some gameplay in replay mod 
2. Exit out of the game 
3. play the replay 
4. 
![2024-06-03_07 02 25](https://github.com/Sinytra/Connector/assets/93085236/dae5decf-4985-4086-892d-45e6db83398d)

...

### Additional context

I don't know if it's player problem or code problem but I hope someone could help me, I tried to delete multiple mods, changed to different models, and when it's a world gen or a block mod it's needs that mod to stay in the folder.

**Comment by ferriarnus** [comment] 2024-06-03 12:16
What mods are you using? And did you change mods between making and watching the replay?

**Comment by jimmytimmy65** [comment] 2024-06-03 14:17
BCLib
Simple Backups
Dank Storage
Rubidium Dynamic Lights
Decorative Pavers
Bad Packets
Xaero's Map - Waystones Compability
BotanyTrees
Create Track Map
Bountiful
SuperMartijn642's Core Lib
BotanyPotsTiers
Chisel Reborn
The Outer End
Multipart Machines: Cooking
Red’s More Structures
RebornStorage
Fabric Language Kotlin
Better Nether
Iron Bookshelves
Botany Pots Ore Planting
Mystical Adaptations
Mekanism: Generators
Amendments
Garnished Botany Pots
Waystones
Jade Addons
Fusion
Cozy Home
Cristel Lib
Better End
Just Enough Breeding
Iron Furnaces
ExtraStorage
Create: Garnished
Integrated API
Sophisticated Backpacks
Tempad
VillagersPlus
Epic Fight
Enhanced Celestials
LionfishAPI
Builder's Delight
EntityCulling
Rings of Ascension
MC Dungeons Artifacts
Sophisticated Storage
Multipart Machines: Storage
Oculus
Just Enough Professions (JEP)
More Mekanism Processing
Iron Shulker Boxes
Simply Swords [Fabric & Forge]
Storage Drawers
Geologic Expansion
Resourceful Lib
Zeta
Aquamirae (Forge)
Refined Storage
CorgiLib
GeckoLib
Sophisticated Core
Iron Spawners
.connector
Hamsters Plus
Mekanism-MoreSolarPanels
Portable Mobs
Connected Glass
Memory Leak Fix
Dynamic Asset Generator
BotanyPots
Deeper and Darker
Mystical Agriculture
Towns and Towers
Corpse
Creative Crafter
TerraBlender (Forge)
Additional Lights
Kambrik
MC Dungeons Weapons
Create: Extended Cogwheels
Tool Leveling+
Create: Structures
Bookshelf
Craftable Spawn Eggs
YUNG's API (Forge)
Jade 🔍
Traveler's Backpack
BuddingCrystals
Multipart Machines: Mining
Shulker+
Resourceful Config
Multipart Machines: Grinding
ReplayMod
Create Ore Excavation
YUNG's Better End Island (Forge)
Xaero's Minimap
Trading Post
Balm
CTD Core
Mo' Glowstone
Litematica
EdivadLib
Cloth Config API (Fabric/Forge/NeoForge)
Structure Gel API
Moonlight Lib
Dimensional Dungeons
Mekanism Tools
The Aether
Animal Feeding Trough
Aether: Lost Content Addon
Cable Tiers
Create: Steam 'n' Rails
MaLiLib
Supplementaries
Mob Grinding Utils
Additional Lanterns
ESSENTIAL Mod
Embeddium (Rubidium) Extra
Just Enough Items
Architectury API (Fabric/Forge/NeoForge)
Xaero's World Map
Mekanism Additions
Easy Villagers
FerriteCore ((Neo)Forge)
The Twilight Forest
EMI Trades (Villager Trading EMI Plugin)
Decorative Lattices
L_Ender 's Cataclysm
Connector Extras
Cucumber Library
Integrated Dungeons and Structures
Extra Disks
EMI Loot
Create Enchantment Industry
When Dungeons Arise - Forge!
Mekanism
Iron Chests
Knaves' Needs
Iron Ender Chests
Multipart Machines: Farming
Create
Embeddium
Blueprint
Mystical Agradditions
Immersive Melodies
Obscure API (Forge)
Athena
Trade Cycling
AeroBlender
Tool Stats
Curios API
Display Case
Lootr (Forge & NeoForge)
EMIffect (Status Effects EMI Plugin)
Kotlin for Forge
Just Enough Resources (JER)
Quark
Puzzles Lib
V1.20.1_Crystalcraft_Unlimited_Raw_Ore_Update
Mystical Agriculture Tiered Crystals
Aethersteel
Do a Barrel Roll
Forgified Fabric API
Integrated Stronghold
EMI
Refined Storage Addons
playerAnimator
The Aether: Redux
More Villager Trades
Sinytra Connector
Weapons of Miracles - epic fight

Tried to change them into different versions, but didn't work :(

**Comment by kakashi1464** [comment] 2024-06-03 17:14
I'd recommend you use the Reforged Play instead of the Replay mod.
https://github.com/ferriarnus/ReForgedPlay/tree/1.20.1

**Comment by jimmytimmy65** [comment] 2024-06-04 08:33
Still showing the same problem :( I even removed the cache and .connector. :(

**Comment by jimmytimmy65** [comment] 2024-06-04 09:14
Ok so for some reason I started a new world, the diamond chests from two different mods worked good, I then added snow pig mod still worked the same but the placement block changed    

![image](https://github.com/Sinytra/Connector/assets/93085236/10c33f86-5293-4ede-b70e-c65671ce1003)
![image](https://github.com/Sinytra/Connector/assets/93085236/d2acf146-a461-4642-9fb7-b4312add4524)


Is it anything to do with the data in the other world that confuses whenever there is someone that adds more mods? And if so is there anyway to reset it without removing any progress of the world?

**Comment by VladisCrafter** [comment] 2024-06-04 10:43
Very, very known bug :<

I still haven't figured it out and the "solution" rn is just to keep the modlist constant or move to a new world whenever you need to add content mods.

**Comment by jimmytimmy65** [comment] 2024-06-04 14:12
Is there any way to change the id inside replay mod?

**Comment by VladisCrafter** [comment] 2024-06-05 07:03
Oh, hello there @ferriarnus. I just wanna report the same thing on your Reforgedplay mod, thinking that you might fix it on your own. This problem occurs on Fabric version too, so my hope slowly disappears :<

**Comment by VladisCrafter** [comment] 2024-06-05 07:04
At least thanks for explanation

**Comment by VladisCrafter** [comment] 2024-06-06 17:09
> This needs a registry sync to fix it (which is easier said then done).
Isn't there a way to just change how Replay mod saves block info? So at least new replays won't have that weak spot, @ferriarnus?

**Comment by Su5eD** [comment] 2024-06-08 17:39
Duplicate of #833

**Closed by Su5eD** 2024-06-08 17:39 UTC
Labels: bug

**Comment by jimmytimmy65** [comment] 2024-07-07 12:18
I fixed it. You just need to make a new world and copy the data from old to new, only the folders not the level.dat

**Comment by re-unknown** [comment] 2024-11-13 23:52
There is a method to repair the level.dat file while keeping player data and other information intact. By using a software called NBTExplorer and deleting the entries for DataPacks, Registries, and LoadingModList, subsequent recordings will work without issues. The last two entries were everything under the fml tree.
