### ISSUE TITLE
Enchancement crash on startup

### ISSUE THREAD

**Issue by Nokunami** [Sinytra/Connector#1470] opened 2024-10-14 02:02 UTC
### Mod Name

Enchancement

### Mod Homepage

https://modrinth.com/mod/enchancement

### Minecraft version

1.21.1

### Describe the bug

Crashes on startup

### Steps to reproduce

1. Install Connector, FFAPI, Connector Extras and Enchancement
2. Launch the game
3. Crashed
...

### Logs

https://mclo.gs/jRMoxda

**Comment by Su5eD** [comment] 2024-10-14 18:46
Duplicate of #1068

**Closed as not planned by Su5eD** 2024-10-14 18:46 UTC
Labels: duplicate
