### ISSUE TITLE
Some intrusive holders were not registered: [Reference{null=PartItem[unregistered]}]

### ISSUE THREAD

**Issue by Colluttorio** [Sinytra/Connector#1171] opened 2024-06-18 10:01 UTC
### Mod Name

Modern Industrialization

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modern-industrialization

### Minecraft version

1.20.1

### Describe the bug

Crash in loading mod

### Steps to reproduce

1. Create a new modpack
2. Copy/install these mods: 
![immagine](https://github.com/Sinytra/Connector/assets/63145139/feb08b28-eaea-435a-9e5e-5adab35df008)
3. Launch it

### Logs

https://gist.github.com/Colluttorio/ff591b9c0f89893536e58f2e77816890

### Additional context

During my test to determine what mod crashed the game, i saw this:

With only Modern Industrialization disabled --> work fine
With only Applied Enegertics disabled --> work fine
With both active: crash

I hope these info are useful.

**Comment by Su5eD** [comment] 2024-06-18 10:39
Duplicate of https://github.com/Sinytra/Connector/issues/404

**Closed by Su5eD** 2024-06-18 10:39 UTC
Labels: compat
