### ISSUE TITLE
C2ME mod don't work for new version Connector

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#453] opened 2023-10-29 17:53 UTC
### Mod Name

C2ME

### Mod Homepage

https://github.com/RelativityMC/C2ME-fabric/releases

### Describe the bug

Now, when the server starts, it crashes the server

### Steps to reproduce

1. Put Connector-1.0.0-beta.22+1.20.1+dev-g8d3c689-full, fabric-api-0.90.4+1.9.29+1.20.1 and C2ME
2. Start Server
3. Use this config **https://mclo.gs/pkKFJOL**
...

### Logs

https://mclo.gs/JQU7boW

**Comment by DonorKrovi** [comment] 2023-10-29 17:59
https://mclo.gs/Miy1OI3 - More Logs

**Comment by Su5eD** [comment] 2023-10-29 18:02
Duplicate of #88

**Comment by DonorKrovi** [comment] 2023-10-29 18:05
> Duplicate of #88

This is completely different, I provided a config with which it worked for me for a month, now after the update it cannot run

**Comment by Su5eD** [comment] 2023-10-29 18:06
hmm alright, I'll see what's up. Is the old issue still relevant then?

**Comment by DonorKrovi** [comment] 2023-10-29 18:09
> hmm alright, I'll see what's up. Is the old issue still relevant then?

In order for the mod to work on Forge, you need to disable **noTickViewDistance**, **threadedWorldGen**

By the way, even in **Fabric**, sometimes it is worth disabling it, as there are many problems

**Comment by DonorKrovi** [comment] 2023-10-29 18:11
It could also be related to **fabric-api-0.90.4+1.9.29+1.20.1**?

**Comment by DonorKrovi** [comment] 2023-10-29 18:15
![image](https://github.com/Sinytra/Connector/assets/60231586/db37d330-4d2c-4f44-bce6-089125992b08)
![image](https://github.com/Sinytra/Connector/assets/60231586/90df83b7-1855-470d-bbea-f411c730992e)
The server works in this scenario of mods

**Closed** 2023-10-30 19:40 UTC
Labels: compat
