### ISSUE TITLE
Iron Spell'n spellsbook error

### ISSUE THREAD

**Issue by car45167** [Sinytra/Connector#899] opened 2024-03-10 15:16 UTC
### Mod Name

Iron's spell n spellsbook

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

### Minecraft version

1.20.1

### Describe the bug

When running iron spells n spellsbook with geckolib fabric (and marium soulslike which is also the only fabric mod installed) The game crashed and log talks about a curio slot and tarnished crown item

### Steps to reproduce

1.Install Iron's spell n spellsbook with geckolib fabric and marium soulslike
2. Enter the game and move around a little
3. The game crashes .
...

### Logs

https://gist.github.com/car45167/7b9eccd8a1034292768fe6fc126ab16c

**Comment by Su5eD** [comment] 2024-03-10 15:36
Duplicate of #231

**Closed by Su5eD** 2024-03-10 15:36 UTC
Labels: compat
