### ISSUE TITLE
The game closes as soon as it opens

### ISSUE THREAD

**Issue by Tonas-o-Trem** [Sinytra/Connector#851] opened 2024-02-21 22:37 UTC
### Mod Name

Sodium

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sodium

### Minecraft version

1.20.1

### Describe the bug

The game closes as soon as it opens

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/Tonas-o-Trem/937d77131532f718d301840edf39cadf#file-gistfile1-txt

**Comment by Su5eD** [comment] 2024-02-21 23:08
Duplicate of #71

**Closed by Su5eD** 2024-02-21 23:08 UTC
Labels: compat
