### ISSUE TITLE
Incompatibility with Flashback

### ISSUE THREAD

**Issue by 3944Realms** [Sinytra/Connector#1368] opened 2024-08-28 02:29 UTC
### Mod Name

Flashback

### Mod Homepage

https://modrinth.com/mod/flashback

### Minecraft version

1.21.1

### Describe the bug

flashback-0.2.0_mapped_moj.1.21.1 inject failed

### Steps to reproduce

1. install
![image](https://github.com/user-attachments/assets/f1ab8ce0-75b3-48ae-ba63-c398f8c8e51a)

2. start the Game

3. then crash
![image](https://github.com/user-attachments/assets/bd598d47-6cd9-4afc-8248-15a75ebbe325)

### Logs

https://gist.github.com/3944Realms/e861bc940e636d01c07e7274de627bdd

```[tasklist]
### Tasks
```

**Comment by Su5eD** [comment] 2024-08-29 18:41
Duplicate of #1353

**Closed by Su5eD** 2024-08-29 18:41 UTC
Labels: compat
