### ISSUE TITLE
Blueprint API crashing with Continuity.

### ISSUE THREAD

**Issue by water-mizuu** [Sinytra/Connector#967] opened 2024-04-04 13:35 UTC
### Mod Name

Continuity

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/continuity

### Minecraft version

1.20.1

### Describe the bug

In an installation that uses Continuity + a resource pack that uses it alongside the Blueprint Library, the game crashes on world load.

### Steps to reproduce

1. Install Connector and related mods (Fabric Reforged & Connector Extras)
2. Install Blueprint and Continuity.
3. Load the default CTM resource packs that Continuity includes.
4. Load any world.
...

### Logs

https://gist.github.com/water-mizuu/d5fde903b8e060b7fb69918bcf129e46

### Additional context

Additionally, this crashes with or without Lazurite.

**Comment by Su5eD** [comment] 2024-04-04 16:00
Possible duplicate of #919, if Blueprint really breaks reloaders

**Comment by Su5eD** [comment] 2024-04-05 19:29
Fixed in Forgified Fabric API [0.92.0+1.11.5+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.92.0+1.11.5+1.20.1).

**Closed by Su5eD** 2024-04-05 19:29 UTC
Labels: compat
