### ISSUE TITLE
Issue or imcompability with the Origins mod 

### ISSUE THREAD

**Issue by ItzBurning2023** [Sinytra/Connector#170] opened 2023-09-03 00:15 UTC
### Describe the bug

So I downloaded the origins mod with other several mods, but when I loaded the game, it crashed. I also tried to load the mod by itself, and it did, however, the mod didn't appear, it was like I was playing mc vanilla, and it also didn't appear in the mod section in minecraft, idk if that can be fixed

![Error](https://github.com/Sinytra/Connector/assets/143913105/2e49faf3-c5dd-4cca-ad60-7aac8e68d1fa)
![Error 2 ](https://github.com/Sinytra/Connector/assets/143913105/36f4433b-dd70-41b5-9222-4e8ff22f60e4)

this is the log: 

[crash-2023-09-02_18.49.26-fml.txt](https://github.com/Sinytra/Connector/files/12504968/crash-2023-09-02_18.49.26-fml.txt)

**Comment by Su5eD** [comment] 2023-09-03 07:28
Duplicate of #161

**Closed by Su5eD** 2023-09-03 07:28 UTC
Labels: bug
