### ISSUE TITLE
The game crashes with replaymod

### ISSUE THREAD

**Issue by MagicWizurdOff** [Sinytra/Connector#676] opened 2024-01-03 17:37 UTC
### Mod Name

Replaymod

### Mod Homepage

https://www.replaymod.com

### Minecraft version

1.20.1

### Describe the bug

Minecraft crashing when I try to load replay mod via connector.

### Steps to reproduce

1. I installed foge 1.20.1 - 47.1.3 - as recommended.
2. I downloaded `Connector-1.0.0-beta232+1.20.1.jar`, `ConnectorExtras-1.9.0+1.20.1.jar`, forgified (`fabric-api-0.9.0+1.10.4+1.20.1.jar`), `replaymod-1.20.1-2.6.14.jar`
3. I ran minecraft. It started loading, always says loadingbootstrap resources, it runs a while and then crashes with this error message:
```
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
```

### Logs

Crash report: https://pastebin.com/d28uRjyi

### Additional context

I did exactly what was shown in this video: https://www.youtube.com/watch?v=LeiirdYoGUc&t

**Comment by Su5eD** [comment] 2024-01-03 18:10
Duplicate of #589

**Closed by Su5eD** 2024-01-03 18:10 UTC
Labels: compat
