### ISSUE TITLE
C2ME mod

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#311] opened 2023-09-22 15:57 UTC
### Mod Name

C2ME mod

### Mod Homepage

https://github.com/RelativityMC/C2ME-fabric/actions/runs/6236508664

### Describe the bug

Crash server

### Steps to reproduce

I found that the server crashes during startup and decided to consider the likely problem, it turned out that if you disable [**noTickViewDistance**]
	# (Default: true) Whether to enable no-tick view distance
	enabled = "false"
In the mod config, the server will be able to run, but this is an important function for the server, I will be very grateful if you solve it in the future, thanks.

### Logs

https://gist.github.com/DonorKrovi/39f8306c6a70a83ebd8a27f0bc41e7ec

**Comment by Su5eD** [comment] 2023-09-22 16:59
Duplicate of #88

**Closed by Su5eD** 2023-09-22 16:59 UTC
Labels: compat
