### ISSUE TITLE
Minecells

### ISSUE THREAD

**Issue by OminousDiscovery** [Sinytra/Connector#1170] opened 2024-06-18 09:32 UTC
### Mod Name

Minecells

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/minecells

### Minecraft version

1.20.1

### Describe the bug

the game crashes

### Steps to reproduce

1. open launcher with minecells, sinytra, and owo (library needed for sinytra)
2. press play
3. game crashes
...

### Logs

https://pastebin.com/BjUTTUg0

**Comment by kakashi1464** [comment] 2024-06-18 09:38
duplicate of #1085

**Closed** 2024-06-18 10:38 UTC
Labels: compat
