### ISSUE TITLE
Blueprint crash on startup

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [Sinytra/Connector#369] opened 2023-10-10 23:40 UTC
### Mod Name

Blueprint

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/blueprint

### Describe the bug

Crashing on startup

### Steps to reproduce

1.Install the Connector, Forgified and Blueprint
2.Start the game

### Logs

https://mclo.gs/9jgOUhc

### Additional context

![image](https://github.com/Sinytra/Connector/assets/24871116/376482f7-953e-4fe2-b37f-2cb0e7bb19d3)

**Comment by Su5eD** [comment] 2023-10-11 12:26
Duplicate of #368

**Closed by Su5eD** 2023-10-11 12:26 UTC
Labels: compat
