### ISSUE TITLE
another better end crash upon start up

### ISSUE THREAD

**Issue by Yay4** [Sinytra/Connector#686] opened 2024-01-07 16:34 UTC
### Mod Name

BetterEnd

### Mod Homepage

https://modrinth.com/mod/betterend

### Minecraft version

1.20.1

### Describe the bug

crash upon start up

### Steps to reproduce

1.
2.
3.
...

### Logs

.

### Additional context

extra note no other mods were installed besides the requirements (BetterEnd, BClib,sinytra connector, and the forgified fabric api port)

Time: 2024-01-07 11:19:31 Description: Initializing game  
net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'! 	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.32+1.20.1.jar%23160!/:1.0.0-beta.32+1.20.1] {} 	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:73) ~[Connector-1.0.0-beta.32+1.20.1.jar%23160!/:1.0.0-beta.32+1.20.1] {} 	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:65) ~[Connector-1.0.0-beta.32+1.20.1-mod.jar%23164!/:1.0.0-beta.32+1.20.1] {re:mixin,re:classloading} 	at net.minecraft.client.Minecraft.handler$zil000$connectormod$earlyInit(Minecraft.java:3923) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.1.84.jar:?] {re:classloading,pl:connector_pre_launch:A,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.1.47.jar:47.1] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.1.47.jar:47.1] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.1.47.jar:47.1] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.1.47.jar:47.1] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {} Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterend'! 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.32+1.20.1.jar%23160!/:1.0.0-beta.32+1.20.1] {} 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.32+1.20.1.jar%23160!/:1.0.0-beta.32+1.20.1] {} 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.32+1.20.1.jar%23160!/:1.0.0-beta.32+1.20.1] {} 	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:53) ~[Connector-1.0.0-beta.32+1.20.1-mod.jar%23164!/:1.0.0-beta.32+1.20.1] {re:mixin,re:classloading} 	... 19 more Caused by: java.lang.InstantiationError: org.betterx.bclib.blocks.BasePathBlock 	at org.betterx.betterend.registry.EndBlocks.<clinit>(EndBlocks.java:123) ~[better-end-4.0.1_mapped_srg_1.20.1.jar%23276!/:?] {re:mixin,re:classloading} 	at org.betterx.betterend.registry.EndBlockEntities.<clinit>(EndBlockEntities.java:17) ~[better-end-4.0.1_mapped_srg_1.20.1.jar%23276!/:?] {re:classloading} 	at org.betterx.betterend.BetterEnd.onInitialize(BetterEnd.java:42) ~[better-end-4.0.1_mapped_srg_1.20.1.jar%23276!/:?] {re:mixin,re:classloading} 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.32+1.20.1.jar%23160!/:1.0.0-beta.32+1.20.1] {} 	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:53) ~[Connector-1.0.0-beta.32+1.20.1-mod.jar%23164!/:1.0.0-beta.32+1.20.1] {re:mixin,re:classloading} 	... 19 more

**Comment by Su5eD** [comment] 2024-01-07 17:59
Plead read the issue template more carefully. Pasting the log into the issue body makes it unreadable.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin

**Comment by geesl** [comment] 2024-01-07 23:28
I think i may have the same problem. Though it does work singleplayer but not when launching a server. Here is my gist: https://gist.github.com/geesl/8c96ec5ba9d0a91abb6a2f9463bda229

**Comment by Su5eD** [comment] 2024-01-08 16:10
> Caused by: java.lang.NoSuchFieldError: CLENT_CONFIG
	at org.betterx.betterend.config.Configs.<clinit>(Configs.java:22) ~[better-end-4.0.10_mapped_srg_1.20.1.jar%23753!/:?]

That is a betterend issue, see quiqueck/BetterEnd/issues/318. Updating should fix it

**Comment by Su5eD** [comment] 2024-01-08 18:51
Closing as cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.

**Closed by Su5eD** 2024-01-08 18:51 UTC
Labels: compat

**Comment by Yay4** [comment] 2024-01-08 19:27
ah sorry I'll try to find it thanks for the informtion
