### ISSUE TITLE
Crash w/ Creative Core & Golden Hopper

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#184] opened 2023-09-04 18:59 UTC
### Describe the bug

game crash with Creative Core & Golden Hopper

### Steps to reproduce

1. install the mods and load the game
2. Wait for the crash
...

### Logs

https://pastebin.com/1fZq9c3c

### Additional context

Custom modpack modlist

- Ad-Astra-Giselle-Addon-forge-1.20.1-5.6.jar

- additionallanterns-1.1.1-forge-mc1.20.jar

- additional_lights-1.20.1-2.1.7.jar

- AdvancedPeripherals-1.20.1-0.7.32b.jar

- AdvancementPlaques-1.20.1-forge-1.4.10.jar

- advgenerators-1.6.0.6-mc1.20.1.jar

- ad_astra-forge-1.20.1-1.15.3.jar

- AE2-Things-1.2.1.jar

- ae2wtlib-15.0.6-beta.jar

- AEAdditions-1.20.1-5.0.2.jar

- AEInfinityBooster-1.20.1-1.0.0+20.jar

- aerialhell-0.6.3_forge1.20.1.jar

- AI-Improvements-1.20-0.5.2.jar

- alchemistry-1.20.1-2.3.3.jar

- alchemylib-1.20.1-1.0.29.jar

- almostunified-forge-1.20.1-0.6.0.jar

- AmbientSounds_FORGE_v5.2.22_mc1.20.1.jar

- amethyst_core-1.2.2+1.20.1.jar

- amethyst_imbuement-1.20.1-10.jar

- AngelRing2-1.20.1-2.2.1.jar

- Apotheosis-1.20.1-7.0.5.jar

- ApothicAttributes-1.20.1-1.1.4.jar

- appleskin-forge-mc1.20.1-2.5.0.jar

- appliedcooking-4.0.0.jar

- appliedenergistics2-forge-15.0.11.jar

- Aquaculture-1.20.1-2.5.0.jar

- ArcaneLanterns-v8.0.0-1.20.1-Forge.jar

- architectury-9.1.12-forge.jar

- argonauts-forge-1.20.1-1.0.4.jar

- ArmorStatues-v8.0.3-1.20.1-Forge.jar

- ars_creo-1.20.1-4.0.1.jar

- ars_nouveau-1.20.1-4.2.4-all.jar

- athena-forge-1.20.1-3.1.0.jar

- AttributeFix-Forge-1.20.1-21.0.2.jar

- backpacked-forge-1.20.1-2.2.5.jar

- BagOfHolding-v8.0.0-1.20.1-Forge.jar

- balm-forge-1.20-7.0.7.jar

- BambooEverything-forge-3.0.3+mc1.20.1.jar

- Barsita-1.20-1.1.2.jar

- BarteringStation-v8.0.0-1.20.1-Forge.jar

- baubley-heart-canisters-1.20.1-1.0.3.jar

- bclib-3.0.13.jar

- bdlib-1.27.0.8-mc1.20.1.jar

- better-end-4.0.10.jar

- better-nether-9.0.9.jar

- BetterAdvancements-1.20.1-0.3.2.161.jar

- BetterTridents-v8.0.1-1.20.1-Forge.jar

- bettervillage-forge-1.20.1-3.2.0.jar

- bibliomania-0.0.1.jar

- biggerreactors-1.20.1-0.6.0-beta.10.1.jar

- BiomesOPlenty-1.20.1-18.0.0.597.jar

- blockui-1.20.1-0.0.91-ALPHA.jar

- bloodmagic-1.20.1-3.3.0-42.homebaked.jar

- blueflame-1.20.0-1.0.3.jar

- blue_skies-1.20.1-1.3.27.jar

- Bookshelf-Forge-1.20.1-20.0.3.jar

- BotanyPots-Forge-1.20.1-13.0.15.jar

- BotanyTrees-Forge-1.20.1-9.0.7.jar

- botarium-forge-1.20.1-2.2.0.jar

- BridgeMaker-1.20.1-2.0.2.jar

- buildinggadgets2-0.2.1.jar

- bwncr-forge-1.20.1-3.17.0.jar

- cabletiers-1.20.1-1.1.jar

- cadmus-forge-1.20.1-1.0.2.jar

- caelus-forge-3.1.0+1.20.jar

- carryon-forge-1.20.1-2.1.2.5.jar

- catalogue-forge-1.20.1-1.7.1.jar

- caupona-1.20.1-0.4.6.jar

- cc-tweaked-1.20.1-forge-1.108.0.jar

- cfm-forge-1.20.1-7.0.0-pre36.jar

- charginggadgets-1.11.0.jar

- charmofundying-forge-6.4.2+1.20.1.jar

- chat_heads-0.10.20-forge-1.20.jar

- chemlib-1.20.1-2.0.17.jar

- Chimes-v2.0.1-1.20.1.jar

- chipped-forge-1.20.1-3.0.1.jar

- chisels-and-bits-forge-1.4.141.jar

- citadel-2.4.3-1.20.1.jar

- clickadv-1.20.1-3.1.jar

- ClickMachine-1.20.1-8.0.1.jar

- cloth-config-11.1.106-forge.jar

- Clumps-forge-1.20.1-12.0.0.3.jar

- colorfulhearts-forge-1.20-4.0.0.jar

- comforts-forge-6.3.3+1.20.1.jar

- CommonCapabilities-1.20.1-2.9.0.jar

- connectedglass-1.1.7-forge-mc1.20.jar

- connectivity-1.20.1-4.5.jar

- Connector-1.0.0-beta.11+1.20.1-full.jar

- constructionwand-1.20.1-2.11.jar

- Controlling-forge-1.20.1-12.0.2.jar

- cookingforblockheads-forge-1.20-16.0.0.jar

- corail_woodcutter-1.20.1-3.0.3.jar

- CorgiLib-forge-1.20.1-4.0.0.4.jar

- corn_delight-1.0.3-1.20.1.jar

- cosmeticarmorreworked-1.20.1-v1a.jar

- crafting-on-a-stick-1.20.1-1.0.2.jar

- craftingtweaks-forge-1.20-18.0.2.jar

- CraftPresence-2.2.2+1.20.1.jar

- CraftTweaker-forge-1.20.1-14.0.14.jar

- crashutilities-8.1.4.jar

- create-1.20.1-0.5.1.d.jar

- create-confectionery1.20.1_v1.0.9.jar

- create-stuff-additions1.20.1_v2.0.4a.jar

- createaddition-1.20.1-1.0.0b.jar

- createbb-1.20.1-3.1.1.jar

- createoreexcavation-1.20-1.3.1.jar

- create_enchantment_industry-1.20.1-for-create-0.5.1
.d-1.2.6.b.jar
- create_jetpack-forge-4.0.1.jar

- create_mechanical_extruder-1.20.1-1.5.2.d-9.jar

- create_mechanical_spawner-1.20.1-0.0.10.d-9.jar

- create_misc_and_things_ 1.20.1_4.0A.jar

- CreativeCore_FORGE_v2.10.34_mc1.20.1.jar

- creativecrafter-1.20.1-1.0.jar

- creeperoverhaul-3.0.1-forge.jar

- cristellib-1.1.1-forge.jar

- Croptopia-1.20.1-FORGE-2.3.2.jar

- ctov-3.3.4.jar

- Cucumber-1.20.1-7.0.1.jar

- cupboard-1.20.1-1.9.jar

- curios-forge-5.2.0+1.20.1.jar

- CustomStartingGear-1.20-2.0.3.jar

- Cyclic-1.20.1-1.12.4.jar

- CyclopsCore-1.20.1-1.18.10.jar

- dankstorage-1.20.1-1.1.jar

- DarkModeEverywhere-1.20.1-1.2.2.jar

- DarkPaintings-Forge-1.20.1-17.0.2.jar

- DarkUtilities-Forge-1.20.1-17.0.2.jar

- deeperdarker-forge-1.20.1-1.2.0.jar

- deepresonance-1.20-5.0.0.jar

- DefaultSettings-1.20.x-4.0.5-Forge.jar

- DeleteWorldsToTrash-v8.0.0-1.20.1-Forge.jar

- DimStorage-1.20.1-8.0.1.jar

- Ding-1.20.1-Forge-1.4.1.jar

- disable_new_world_screen-forge-1.20.1-1.1.0.jar

- DistinguishedPotions-v8.0.1-1.20.1-Forge.jar

- doapi-1.2.7-forge.jar

- DoggyTalentsNext-1.20.1-1.15.2.jar

- domum_ornamentum-1.20-1.0.128-BETA-universal.jar

- drippyloadingscreen_forge_2.2.4_MC_1.20.1.jar

- Dungeon Crawl-1.20.1-2.3.14.jar

- durabilitytooltip-1.1.4-forge-mc1.20.jar

- EasyAnvils-v8.0.1-1.20.1-Forge.jar

- EasyMagic-v8.0.1-1.20.1-Forge.jar

- easy_mob_farm_1.20.1-6.3.0.jar

- easy_piglins-1.20.1-1.0.1.jar

- easy_villagers-1.20.1-1.0.12.jar

- eccentrictome-1.20.1-1.10.1.jar

- EchoChest-v8.0.0-1.20.1-Forge.jar

- EdivadLib-1.20.1-2.0.1.jar

- EffectDescriptions-v8.0.2-1.20.1-Forge.jar

- elevatorid-1.20.1-1.8.15.jar

- elytraslot-forge-6.3.0+1.20.1.jar

- EnchantingInfuser-v8.0.1-1.20.1-Forge.jar

- EnchantmentDescriptions-Forge-1.20.1-17.0.5.jar

- EnderIO-1.20.1-6.0.18-alpha.jar

- Enderite-CJ-forge-mc1.20.1-1.4.1.jar

- endersdelight-1.20.1-1.0.1.jar

- endertrigon-1.20.1-1.0.jar

- EnderZoology-v8.0.1-1.20.1-Forge.jar

- ends_delight-1.20.1-1.0.1.jar

- energizedpower-1.20.1-2.1.0.jar

- entangled-1.3.16-forge-mc1.20.jar

- entityculling-forge-1.6.2-mc1.20.jar

- EvilCraft-1.20.1-1.2.28.jar

- Excavar-1.20.1-3.1.0.jar

- Exchangers-1.20.1-3.5.1.jar

- expandedstorage-10.0.0-beta.3+1.20-forge.jar

- ExtendedAE-1.20-0.1.10-forge.jar

- ExtraDisks-1.20.1-3.0.0.jar

- ExtraStorage-1.20.1-4.0.3.jar

- extremesoundmuffler-3.39-forge-1.20.jar

- fabric-api-0.87.0+1.9.8+1.20.1.jar

- fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar

- fancymenu_forge_2.14.9-1_MC_1.20.1.jar

- farlanders-1.20.1-1.4.1.jar

- FarmersDelight-1.20.1-1.2.3.jar

- farmingforblockheads-forge-1.20-14.0.1.jar

- farsight-1.20.1-3.3.jar

- FastFurnace-1.20.1-8.0.1.jar

- FastLeafDecay-31.jar

- FastSuite-1.20.1-5.0.1.jar

- ferritecore-6.0.0-forge.jar

- findme-3.1.0-forge.jar

- fixexperiencebug-1.20-46.2.2.jar

- flib-1.20.1-0.0.11.jar

- flickerfix-1.20.1-4.0.1.jar

- FluxNetworks-1.20.1-7.2.0.14.jar

- forbidden_arcanus-1.20.1-2.2.0.jar

- forcecraft-1.20.1-4.0.0.jar

- FORGE-blanced_crates1.7.5-1.20.1.jar

- ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar

- FramedBlocks-9.0.3.jar

- framework-forge-1.20.1-0.6.16.jar

- frosted-friends-1.20.1-1.0.7.jar

- fuelgoeshere-1.20.0-1.0.1.jar

- fulleng-forge-1.6-1.20.1.jar

- functionalstorage-1.20.1-1.2.2.jar

- fusion-1.0.5a-forge-mc1.20.jar

- fzzy_core-0.2.7+1.20.1.jar

- GatewaysToEternity-1.20.1-4.1.1.jar

- geckolib-forge-1.20.1-4.2.2.jar

- generatorgalore-1.20.0-1.1.0.jar

- GeOre-1.20.1-2.4.0.jar

- GeOre_Nouveau-1.20.1-0.3.1.jar

- getittogetherdrops-forge-1.20-1.3.jar

- goblintraders-forge-1.20.1-1.9.2.jar

- goldenhopper-forge-1.20.1-1.4.1.jar

- good_nights_sleep-1.20.1-1.3.1.jar

- gpumemleakfix-1.20.1-1.6.jar

- gtceu-forge-1.20.1-1.0.11.a.jar

- GunpowderLib-1.20-2.2.jar

- handcrafted-forge-1.20.1-3.0.1.jar

- HangGlider-v8.0.1-1.20.1-Forge.jar

- harvestwithease-1.20.1-7.0.0.2-forge.jar

- heracles-forge-1.20.1-1.0.4.jar

- HostileNeuralNetworks-1.20.1-5.1.3.jar

- hyperbox-1.20.1-4.0.0.0.jar

- Iceberg-1.20.1-forge-1.1.13.jar

- IllagerInvasion-v8.0.2-1.20.1-Forge.jar

- industrial-foregoing-1.20.1-3.5.9.jar

- IntegratedDynamics-1.20.1-1.18.0.jar

- IntegratedTunnels-1.20.1-1.8.22.jar

- inventoryessentials-forge-1.20-8.0.0.jar

- inventorygenerators-1.20.1-1.0.1.jar

- InventoryProfilesNext-forge-1.20-1.10.7.jar

- ironfurnaces-1.20-3.9.0.jar

- IronJetpacks-1.20.1-7.0.0.jar

- irons_spellbooks-1.20.1-1.2.1.jar

- itemcollectors-1.1.8-forge-mc1.20.jar

- ItemPhysicLite_FORGE_v1.6.1_mc1.20.jar

- JAOPCA-1.20.1-4.4.0.1.jar

- JCPlugin-1.17.x-1.20.x-4.0.4-Forge.jar

- jei-1.20.1-forge-15.2.0.27.jar

- jmi-forge-1.20.1-0.14-45.jar

- journeymap-1.20.1-5.9.12-forge.jar

- jumpboat-1.20.0-1.0.5.jar

- JustEnoughProfessions-forge-1.20.1-3.0.1.jar

- JustEnoughResources-1.20.1-1.4.0.238.jar

- kjlib-1.20.1-1.0.0.jar

- konkrete_forge_1.6.1-2_MC_1.20.jar

- kotlinforforge-4.4.0-all.jar

- laserio-1.6.5.jar

- ldlib-forge-1.20.1-1.0.19.b.jar

- LegendaryTooltips-1.20.1-forge-1.4.5.jar

- letmedespawn-1.1.1.jar

- letsdo-meadow-forge-1.3.0.jar

- letsdo-vinery-forge-1.4.4.jar

- libIPN-forge-1.20-4.0.0.jar

- libraryferret-forge-1.20.1-4.0.0.jar

- LibX-1.20.1-5.0.5.jar

- loadingbackgrounds-1.1.0-forge.jar

- loginar-storage-1.20.1-1.2.1.jar

- logprot-1.20.1-3.1.jar

- lootr-1.20-0.7.30.73.jar

- Lunar-forge-1.20.1-0.1.6.jar

- macawsbridgesbop-1.20-1.1.jar

- macawsroofsbop-1.20-1.0.jar

- MagnumTorch-v8.0.0-1.20.1-Forge.jar

- mahoutsukai-1.20.1-v1.34.54.jar

- matc-1.6.0.jar

- mcjtylib-1.20-8.0.2.jar

- mcw-bridges-2.1.1-mc1.20.1forge.jar

- mcw-doors-1.1.0forge-mc1.20.1.jar

- mcw-fences-1.0.7-mc1.20.1forge.jar

- mcw-lights-1.0.6-mc1.20.1forge.jar

- mcw-paintings-1.0.4forge-mc1.20.jar

- mcw-paths-1.0.3forge-mc1.20.1.jar

- mcw-roofs-2.2.4-mc1.20.1forge.jar

- mcw-trapdoors-1.1.1-mc1.20.1forge.jar

- mcwfencesbop-1.20-1.0.jar

- mealapi-0.3.2+1.20.jar

- megacells-forge-2.1.0-1.20.1.jar

- Mekanism-1.20.1-10.3.9.homebaked-all.jar

- merequester-forge-1.20.1-1.1.4.jar

- MetalBundles-v8.0.0-1.20.1-Forge.jar

- mffs-5.1.5-all.jar

- midnightlib-forge-1.4.1.jar

- mighty_mail-forge-1.20.1-1.0.13.jar

- Miniature Power Plant-47.0.0.jar

- mininggadgets-1.15.3.jar

- MiniumStone-v8.0.0-1.20.1-Forge.jar

- MobLassos-v8.0.0-1.20.1-Forge.jar

- MobPlaques-v8.0.0-1.20.1-Forge.jar

- mob_grinding_utils-1.20.1-1.0.2.jar

- modelfix-1.14.jar

- modernfix-forge-5.7.2+mc1.20.1.jar

- modonomicon-1.20.1-forge-1.39.0.jar

- modular-routers-12.0.2+mc1.20.1.jar

- moonlight-1.20-2.8.16-forge.jar

- moredragoneggs-4.0.jar

- moreoverlays-1.22.1-mc1.20.jar

- morered-1.20.1-4.0.0.4.jar

- MouseTweaks-forge-mc1.20-2.25.jar

- mowlib-0.4.54.jar

- multipiston-1.20-1.2.31-ALPHA.jar

- MutantMonsters-v8.0.3-1.20.1-Forge.jar

- MyServerIsCompatible-1.20-1.0.jar

- mysterious_mountain_lib-1.2.7-1.20.jar

- MysticalAgradditions-1.20.1-7.0.1.jar

- MysticalAgriculture-1.20.1-7.0.3.jar

- MysticalCustomization-1.20.1-5.0.0.jar

- NaturesAura-39.0.jar

- NaturesCompass-1.20.1-1.11.2-forge.jar

- NetherChested-v8.0.1-1.20.1-Forge.jar

- netherportalfix-forge-1.20-13.0.0.jar

- nightlights-1.20.1-1.1.jar

- NoChatReports-FORGE-1.20.1-v2.2.2.jar

- oauth-account-manager-forge-1.20.1-1.0.0.4.jar

- Obscure-Tooltips-2.2.jar

- occultism-1.20.1-1.87.1.jar

- oceansdelight-1.0.2-1.20.jar

- OpenLoader-Forge-1.20.1-19.0.2.jar

- owo-lib-0.11.1+1.20.jar

- PackingTape-1.20-0.14.1.jar

- Patchouli-1.20.1-81-FORGE.jar

- PermanentSponges-v8.0.0-1.20.1-Forge.jar

- phantasmic-1.20.1-0.2.5.jar

- phosphophyllite-1.20.1-0.7.0-alpha.jar

- PickUpNotifier-v8.0.0-1.20.1-Forge.jar

- PigPen-Forge-1.20.1-15.0.2.jar

- PineappleDelight-Forge-1.0.6-Fix.jar

- pipez-1.20.1-1.1.5.jar

- Placebo-1.20.1-8.3.7.jar

- platforms-forge-1.20.1-1.0.jar

- player-animation-lib-forge-1.0.2-rc1+1.20.jar

- PlentyPlates-v8.0.0-1.20.1-Forge.jar

- pneumaticcraft-repressurized-6.0.4+mc1.20.1.jar

- polylib-forge-1200.0.2-build.85.jar

- polymorph-forge-0.49.0+1.20.1.jar

- PortableHole-v8.0.0-1.20.1-Forge.jar

- Potion-Blender-1.20-FORGE-1.1.0.jar

- potionsmaster-1.20.1-47.1.70-0.6.0.jar

- Powah-5.0.2.jar

- primalmagick-4.0.3.jar

- Prism-1.20.1-forge-1.0.5.jar

- productivebees-1.20.1-12.1.9.jar

- prometheus-forge-1.20.1-1.1.0.jar

- PuzzlesLib-v8.0.24-1.20.1-Forge.jar

- pylons-1.20.1-4.2.0.jar

- quartz-1.20.1-0.2.0-alpha.jar

- railcraft-reborn-1.20.1-1.0.4.jar

- rangedpumps-1.1.0.jar

- rechiseled-1.1.2a-forge-mc1.20.jar

- rechiseledcreate-1.0.0a-forge-mc1.20.jar

- refinedcooking-4.0.0.jar

- refinedstorage-1.12.3.jar

- refinedstorageaddons-0.10.0.jar

- reliquary-1.20.1-2.0.36.1199.jar

- repurposed_structures-7.1.5+1.20.1-forge.jar

- resourcefulconfig-forge-1.20.1-2.1.0.jar

- resourcefullib-forge-1.20.1-2.1.10.jar

- respawnobelisks-2.3-a.jar

- rftoolsbase-1.20-5.0.1.jar

- rftoolsbuilder-1.20-6.0.0.jar

- rftoolscontrol-1.20-7.0.0.jar

- rftoolsdim-1.20-11.0.0.jar

- rftoolspower-1.20-6.0.0.jar

- rftoolsstorage-1.20-5.0.0.jar

- rftoolsutility-1.20-6.0.1.jar

- riverredux-0.3.1.jar

- RootsClassic-1.20.1-1.3.1.jar

- RSInfinityBooster-1.20.1-1.0+32.jar

- rsinsertexportupgrade-1.20.1-1.1.jar

- rsrequestify-1.20.1-2.3.2.jar

- Runelic-Forge-1.20.1-18.0.2.jar

- sandwichable-1.3.1+1.20.1.jar

- ScalableCatsForce-3.3.0-build-2-with-library.jar

- Searchables-forge-1.20.1-1.0.1.jar

- sebastrnlib-4.0.0.jar

- serversleep-datapack.jar

- shetiphiancore-forge-1.20.1-1.0.jar

- show-me-your-skin-1.6.11+1.20.jar

- silent-gear-1.20.1-3.5.1.jar

- silent-lib-1.20.1-8.0.0.jar

- SimpleBackups-1.20.1-3.1.2.jar

- simplemagnets-1.1.9-forge-mc1.20.jar

- simpletomb-1.20.1-1.3.0.jar

- simplylight-1.20.1-1.4.5-build.49.jar

- sliceanddice-forge-3.1.1.jar

- SmartBrainLib-forge-1.20-1.11.jar

- smoothchunk-1.20.1-3.1.jar

- snowyspirit-1.20-2.2.5.jar

- solapplepie-1.20.1-2.3.0.jar

- solarcraft-3.2.2-1.20.1.jar

- SolarGeneration-1.20.1-6.0.2.jar

- soulshards-1.20-1.3.4.jar

- soundphysics-forge-1.20.1-1.2.1.jar

- spark-1.10.42-forge.jar

- spells_and_shields-1.20.1-2.13.1.jar

- SpikySpikes-v8.0.1-1.20.1-Forge.jar

- Statues-1.20.1-0.3.6.4.jar

- Steam_Rails-1.5.0+forge-mc1.20.1-build.14.jar

- stevescarts-1.20.1-1.1.13.jar

- Stoneworks-v8.0.0-1.20.1-Forge.jar

- StrawStatues-v8.0.1-1.20.1-Forge.jar

- Structory_1.20.1_v1.3.2.jar

- Structory_Towers_1.20.1_v1.0.3.jar

- StructureCompass-1.20.1-2.0.5.jar

- structure_gel-1.20.1-2.13.1.jar

- structurize-1.20.1-1.0.631-BETA.jar

- StylishEffects-v8.0.0-1.20.1-Forge.jar

- subterrestrial-forge-1.20-2.2.0.jar

- Super Factory Manager-1.20-4.10.2.jar

- supermartijn642configlib-1.1.8-forge-mc1.20.jar

- supermartijn642corelib-1.1.12a-forge-mc1.20.jar

- supplementaries-1.20-2.5.28.jar

- TaxFreeLevels-1.3.5-forge-1.19.jar

- TechReborn-5.8.7.jar

- tech_enhanced-1.0.3.jar

- tempad-forge-1.20.1-2.1.1.jar

- TerraBlender-forge-1.20.1-3.0.0.169.jar

- Terralith_1.20.1_v2.4.5.jar

- theoneprobe-1.20.1-10.0.1.jar

- thermoo-1.6.1.jar

- theurgy-1.20.1-1.6.4.jar

- The_Undergarden-1.20.1-0.8.8.jar

- tidal-towns-1.2.jar

- TiledCauldron-1.20-5.0.jar

- tinyredstone-1.20-5.0.1.jar

- TipTheScales-forge-1.20.1-9.0.0.1.jar

- titanium-1.20.1-3.8.21.jar

- ToastControl-1.20.1-8.0.3.jar

- ToolBelt-1.20-1.20.0.jar

- ToolStats-Forge-1.20.1-16.0.3.jar

- totw_modded-1.0.1-1.20.1.jar

- Towns-and-Towers-1.11-Fabric+Forge.jar

- TradingPost-v8.0.1-1.20.1-Forge.jar

- trashcans-1.0.18b-forge-mc1.20.jar

- trashslot-forge-1.20-15.0.0.jar

- TravelersBackpack-1.20.1-9.1.4.jar

- trinkets-3.7.1.jar

- twigs-1.20.1-3.1.0-forge.jar

- twilightdelight-2.0.2.jar

- twilightforest-1.20.1-4.3.1809-universal.jar

- UniversalEnchants-v8.0.0-1.20.1-Forge.jar

- universalgrid-1.20.1-1.0.jar

- u_team_core-forge-1.20.1-5.1.4.269.jar

- valhelsia_core-forge-1.20.1-1.1.1.jar

- victus-0.1.14+1.20.jar

- villagertools-1.20.1-1.0.3.jar

- visualoverhaul-forge-5.0.1.jar

- VisualWorkbench-v8.0.0-1.20.1-Forge.jar

- voidtotem-forge-1.20-3.0.1.jar

- waystones-forge-1.20-14.0.1.jar

- well-1.20.1-1.0.0.jar

- WitherSkeletonTweaks-1.20.1-9.0.1.jar

- xnet-1.20-6.0.1.jar

- xtonesreworked-1.0.2-1.20.1-47.0.1.jar

- YeetusExperimentus-Forge-2.3.1-build.6+mc1.20.1.jar

- [1.20.1] SecurityCraft v1.9.7-beta2.jar

**Comment by Lolothepro** [comment] 2023-09-04 19:00
duplicate of https://github.com/Sinytra/Connector/issues/122

**Closed** 2023-09-04 19:02 UTC
Labels: bug

**Comment by EndangeredNayla** [comment] 2023-09-04 19:24
This is not a duplicate as that issue has been closed

**Comment by Su5eD** [comment] 2023-09-04 19:28
The issue has been fixed, and the patch will be available in the next release
