### ISSUE TITLE
hephaestus/porting lib crash

### ISSUE THREAD

**Issue by xg787** [Sinytra/Connector#1259] opened 2024-07-22 13:32 UTC
### Mod Name

hephaestus

### Mod Homepage

https://modrinth.com/mod/hephaestus

### Minecraft version

1.20.1

### Describe the bug

loading crash

### Steps to reproduce

1.add mod then crash

### Logs

https://gist.github.com/xg787/48548a2aaf12d3153d5307532713fc27

**Comment by Su5eD** [comment] 2024-07-22 14:13
Duplicate of #74

**Closed by Su5eD** 2024-07-22 14:13 UTC
Labels: compat

**Comment by xg787** [comment] 2024-07-22 14:50
![um](https://github.com/user-attachments/assets/a6763ba2-a7e2-4d67-9463-b99aa7035cdf)
the error i have is completely different from the one in #74

**Comment by alchemyyy** [comment] 2024-08-22 22:27
https://github.com/Sinytra/Connector/issues/74

Is where this issue is being tracked. If you read through the comments there you'll understand the problem in more depth.
