### ISSUE TITLE
Conquest Reforged : Encountered error while transforming jar [...] (Porting Lib)

### ISSUE THREAD

**Issue by Yldales** [Sinytra/Connector#1181] opened 2024-06-23 18:59 UTC
### Mod Name

Conquest Reforged

### Mod Homepage

https://modrinth.com/mod/conquest-reforged

### Minecraft version

1.20.1

### Describe the bug

The game crashes when loading.

### Steps to reproduce

1. Download Forge [47.2.30](https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.2.30/forge-1.20.1-47.2.30-installer.jar).
2. Download [Connector 1.0.0-beta.44+1.20.1](https://cdn.modrinth.com/data/u58R1TMW/versions/74Z0Kmgx/Connector-1.0.0-beta.44%2B1.20.1.jar).
3. Download [[1.20.1] Forgified Fabric API 0.92.2+1.11.8+1.20.1](https://cdn.modrinth.com/data/Aqlf1Shp/versions/D3EZO1Kr/fabric-api-0.92.2%2B1.11.8%2B1.20.1.jar).
4. Download [ConnectorExtras 1.11.1+1.20.1](https://cdn.modrinth.com/data/FYpiwiBR/versions/OoUDmJIb/ConnectorExtras-1.11.1%2B1.20.1.jar).
5. Download [Conquest Reforged 1.1.3](https://cdn.modrinth.com/data/s93iojuG/versions/I6ojyheZ/ConquestRefabricated-1.1.3.jar).
6. Start Minecraft.

### Logs

https://pastebin.com/raw/9XTbF5bw

### Additional context

The issue _seems_ to be related with [Porting Lib](https://modrinth.com/mod/porting_lib).

**Comment by Su5eD** [comment] 2024-07-22 14:14
Duplicate of #880

**Closed by Su5eD** 2024-07-22 14:14 UTC
Labels: compat
