### ISSUE TITLE
Rubidium 0.7.0a incompatible with better nether and better end

### ISSUE THREAD

**Issue by RoomAlex68** [Sinytra/Connector#202] opened 2023-09-06 04:51 UTC
Better nether and better end crash with rubidium when creating a new world.

Mod links here:
https://modrinth.com/mod/betterend

https://modrinth.com/mod/betternether?hl=en-US

https://modrinth.com/mod/bclib

https://modrinth.com/mod/rubidium

**Comment by Su5eD** [comment] 2023-09-06 05:01
Please provide a crash report and your debug.log

**Comment by RoomAlex68** [comment] 2023-09-06 14:17
![crash-2023-09-05_21.07.13-client.txt](https://github.com/Sinytra/Connector/files/12538785/crash-2023-09-05_21.07.13-client.txt)

**Comment by RoomAlex68** [comment] 2023-09-06 16:41
![crash-2023-09-05_21.07.13-client.txt](https://github.com/Sinytra/Connector/files/12538785/crash-2023-09-05_21.07.13-client.txt)

 It doesn't crash when I use Rubidium 6.5 and Oculus 1.6.4(1.20.1

**Comment by rainysux** [comment] 2023-09-06 16:46
no its just that rubidium 0.7a isnt compatible with oculus

**Comment by tharrmeehan** [comment] 2023-09-06 16:49
oculus does not seem to be in the modlist.

**Comment by 1straycat** [comment] 2023-09-06 21:04
I recommend using Embeddium ([link](https://legacy.curseforge.com/minecraft/mc-mods/embeddium)) rather than Rubidium 0.7.0+. It fixes many of Rubidium's incompatibilities, and I've been using it with Connector and Better Nether with no issue.

**Comment by RoomAlex68** [comment] 2023-09-07 22:24
It embeddium too

**Comment by RoomAlex68** [comment] 2023-09-07 22:31
Does Oculus work with Embeddium?

**Comment by RoomAlex68** [comment] 2023-09-07 23:06
It Crashed with Embeddium too.

![crash-2023-09-07_15.33.35-client.txt](https://github.com/Sinytra/Connector/files/12554011/crash-2023-09-07_15.33.35-client.txt)

**Comment by RoomAlex68** [comment] 2023-09-07 23:09
It Crashed with Embeddium 0.1.3 and 0.1.2
Mod Link here: 
https://www.curseforge.com/minecraft/mc-mods/embeddium

Crash log here:
![crash-2023-09-07_16.07.55-client.txt](https://github.com/Sinytra/Connector/files/12554030/crash-2023-09-07_16.07.55-client.txt)

**Comment by Su5eD** [comment] 2023-09-08 05:54
> Shader compilation failed, see log for details

Can you please provide your debug.log?

**Comment by RoomAlex68** [comment] 2023-09-09 17:08
It even crashed with Embeddium 0.1.4 

Here is crash and Latest Log: 

![crash-2023-09-09_09.52.43-client.txt](https://github.com/Sinytra/Connector/files/12566315/crash-2023-09-09_09.52.43-client.txt)

![converted_fileproinfo_latest (1).txt](https://github.com/Sinytra/Connector/files/12566317/converted_fileproinfo_latest.1.txt)

**Comment by Su5eD** [comment] 2023-09-09 18:11
> [09:52:34] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.vsh: ERROR: 0:110: '>>' :  wrong operand types  no operation '>>' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:110: 'xffffu' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 2 compilation errors.  No code generated.

It complains about shader syntax, though I don't know how this could be influenced by other mods unless they mess with shader code. I'll see if I can reproduce the issue myself.

**Comment by RoomAlex68** [comment] 2023-09-09 23:22
Any results?

**Comment by RoomAlex68** [comment] 2023-09-12 18:57
Su5eD have you got any results?

**Comment by MarsliZiya** [comment] 2023-09-13 15:40
> It doesn't crash when I use Rubidium 6.5 and Oculus 1.6.4(1.20.1)
which version of FFAPI and Connector do you use? it crashes with this log:
[crash-2023-09-13_18.17.40-client.txt](https://github.com/Sinytra/Connector/files/12599479/crash-2023-09-13_18.17.40-client.txt)

**Comment by RoomAlex68** [comment] 2023-09-13 15:56
I used it with Rubidium 0.6.5 and Oculus 1.6.4 and rubidium-extra-0.4.20+mc1.20-build.91 and it didn't crash for me

**Comment by RoomAlex68** [comment] 2023-09-13 15:58
I used the Connector Beta 13 and [1.20.1] Forgified Fabric API 0.88.1+1.9.11+1.20.1

**Comment by Su5eD** [comment] 2023-09-18 19:45
I tried this out with the following mods and everything runs fine:
- Connector beta 14
- FFAPI 0.88.1+1.9.11+1.20.1
- Rubidium 0.7.0a
- BCLib 3.0.13
- Better End 4.0.10

Closing as cannot reproduce. Given the shader compile error message, I suspect this is a driver issue on your end. Try updating your drivers / using a different os or computer to see if the issue persists.

**Closed by Su5eD** 2023-09-18 19:45 UTC
Labels: needs info
