### ISSUE TITLE
ClientCommands Incompatability

### ISSUE THREAD

**Issue by thundercreeper10** [Sinytra/Connector#487] opened 2023-11-07 19:47 UTC
### Mod Name

ClientCommands

### Mod Homepage

https://modrinth.com/mod/client-commands

### Describe the bug

Crash on launch

### Steps to reproduce

1.Use the Sinytra connector with the Forgified API
2.Add Client Commands
3.Crash!
...

### Logs

https://mclo.gs/POrTVm3

**Comment by Su5eD** [comment] 2023-11-07 20:03
Duplicate of #441

**Closed by Su5eD** 2023-11-07 20:03 UTC
Labels: compat
