### ISSUE TITLE
Create Addon 'Destroy' Crashes With Connector

### ISSUE THREAD

**Issue by CraftyZombie** [Sinytra/Connector#995] opened 2024-04-09 04:30 UTC
### Mod Name

destroy

### Mod Homepage

https://modrinth.com/mod/destroy

### Minecraft version

1.20.1

### Describe the bug

The game crashes on startup.

### Steps to reproduce

1. Create an installation with Connector, Destroy, and dependencies.
2. Run game.

### Logs

https://gist.github.com/CraftyZombie/7c50b012135c8ee27ca3f50dd3a75389

### Additional context

All logs and the crash report are located in the gist.

**Comment by Su5eD** [comment] 2024-04-09 06:02
Duplicate of https://github.com/Sinytra/ForgifiedFabricAPI/issues/115

**Closed by Su5eD** 2024-04-09 06:02 UTC
Labels: compat

**Comment by CraftyZombie** [comment] 2024-04-10 02:41
Apologies, forgot to check the other repository.
