### ISSUE TITLE
[1.21.1] Game has to be launched around 5 times for it to not crash and load with Better Nether / Better End.

### ISSUE THREAD

**Issue by VOLKOUL** [Sinytra/Connector#1341] opened 2024-08-18 12:20 UTC
### Mod Name

Better X Mods

### Mod Homepage

https://www.curseforge.com/members/quiqueck/projects

### Minecraft version

1.21.1

### Describe the bug

Initially I thought that the game wouldn't launch at all, but after like 5 attempts it suddenly worked. 

### Steps to reproduce

Install BCLib, BetterNether, BetterEnd, WunderLib and WorldWeaver (last two are required for 1.21.x afaik)

I also have Embeddium, ModernFix, FerriteCore, ETF, EMF, Continuity, Connector, Connector Extras and FFAPI installed. 

### Logs

There were two different logs. One on first launch when it crashed and then I disabled every other mod that could potentially cause issues and the second log for every next crash that had the minimal set of mods installed (listed above) The second log had more errors, surprisingly. LOG1: https://mclo.gs/DfGvQDm LOG2: https://mclo.gs/vwjYmIg

### Additional context

My guess is that the new BetterX dependencies introduced in 1.21.x had to be individually "reviewed" by Connector, as the number of startup crashes there were was the same with the number of variants of said dependencies (I think). I mean the variants listed in the mod list inside the game. Just like FFAPI is separated into multiple things, the new BetterX dependencies are too. This is probably a completely wrong, wild and stupid assumption, but I have nothing else to connect it to lol. Anyways, after the game finally launched normally, everything appeared to be working smoothly, except for the world generation in the End, as described in this issue: https://github.com/Sinytra/Connector/issues/1331

**Comment by Su5eD** [comment] 2024-08-18 13:08
Duplicate of #1338

**Closed as not planned by Su5eD** 2024-08-18 13:08 UTC
Labels: duplicate
