### ISSUE TITLE
carpet mod doesnt work

### ISSUE THREAD

**Issue by forgolotl** [Sinytra/Connector#596] opened 2023-12-11 01:48 UTC
### Mod Name

carpet 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/carpet

### Describe the bug

crashes on start up

### Steps to reproduce

1. start minecraft (forge 47.2.6-47.1.3 sinytra 15-29)
2. minecraft crash
3.
...

### Logs

https://mclo.gs/bPgLB6h

### Additional context

goo goo ga ga

**Comment by Su5eD** [comment] 2023-12-11 06:54
Duplicate of #296

**Closed** 2023-12-11 06:54 UTC
Labels: compat
