### ISSUE TITLE
Incompatiblity with More Axolotl by KxmischesDomi

### ISSUE THREAD

**Issue by BluSodah** [Sinytra/Connector#918] opened 2024-03-19 08:28 UTC
### Mod Name

More Axolotl

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/more-axolotls

### Minecraft version

1.20.1

### Describe the bug

Failing during launch

### Steps to reproduce

1.Have the connector and reforiged fabric mod (i tried several versions connector and reforgied fabric and presented the last crash along with the newest crash) and More Axolotl 2.0.1-1.20
-also had infinite banners installed which works great with your mod
2. Launch the game
3. Watch it fail to launch because it said its unable to read 'main' due to errors
...

### Logs

<script src="https://gist.github.com/BluSodah/478be94790a0d2ada748f8fb523dff23.js"></script>

### Additional context

[crash-2024-03-19_04.18.26-client.txt](https://github.com/Sinytra/Connector/files/14647647/crash-2024-03-19_04.18.26-client.txt)

**Comment by Su5eD** [comment] 2024-03-19 19:19
Duplicate of #674

**Closed by Su5eD** 2024-03-19 19:19 UTC
Labels: compat
