### ISSUE TITLE
Valkyrien Skies mod crash

### ISSUE THREAD

**Issue by xg787** [Sinytra/Connector#1199] opened 2024-06-30 03:44 UTC
### Mod Name

Valkyrien Skies

### Mod Homepage

https://modrinth.com/mod/valkyrien-skies

### Minecraft version

1.20.1

### Describe the bug

loading crash

### Steps to reproduce

1.load valk with some other mod (i dont know mod specifically crashes it)
2.crash

### Logs

https://gist.github.com/xg787/2a895debe1c3815fe272060a2b2602eb

### Additional context

i dont know what combination of mods crashes it but i know it is connector related as it loads just fine without connector

**Comment by xg787** [comment] 2024-06-30 03:45
crash report https://gist.github.com/xg787/3a7c7167d16471f422b5ac4810a1330b

**Comment by RoomAlex68** [comment] 2024-06-30 05:29
ConnectorExtras#33

**Comment by RoomAlex68** [comment] 2024-06-30 05:30
ConnectorExtras#33

**Comment by Su5eD** [comment] 2024-06-30 07:35
Duplicate of https://github.com/Sinytra/ConnectorExtras/issues/33

**Closed by Su5eD** 2024-06-30 07:35 UTC
Labels: compat
