### ISSUE TITLE
Sign sheet materials initialization being flagged on dedicated server

### ISSUE THREAD

**Issue by Doctor-Duck** [Sinytra/Connector#357] opened 2023-10-05 03:44 UTC
### Describe the bug

java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/Sheets for invalid dist DEDICATED_SERVER

### Steps to reproduce

1. Launch server.
2. Crash occurs when loading Connector mod.
3. Failure message: Connector (connectormod) encountered an error during the complete event phase
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/Sheets for invalid dist DEDICATED_SERVER

Using Connector-1.0.0-beta.17+1.20.1-full

### Logs

https://pastebin.com/5qVhjcz6

**Comment by Su5eD** [comment] 2023-10-05 07:08
Duplicate of #340; will be fixed in the next release

**Closed by Su5eD** 2023-10-05 07:08 UTC
Labels: bug
