### ISSUE TITLE
Continuity and Blueprint

### ISSUE THREAD

**Issue by OctaveMutt** [Sinytra/Connector#1234] opened 2024-07-16 04:49 UTC
### Mod Name

Blueprint

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/blueprint

### Minecraft version

1.20.1

### Describe the bug

Blueprint disables connected textures when installed with Continuity

### Steps to reproduce

1. Install Sinytra Connector/Forgified Fabric API, Continuity, and blueprint
2. launch game/world
3. Enable recourse pack that uses connected textures
4. Connected textures do not work
...

### Logs

https://gist.github.com/OctaveMutt/1b353914d93049ca7a98a6fdce2d294e

### Additional context

- Blueprint 1.20.1 - 7.1.0
- Connector 1.0.0-beta.44+1.20.1
- fabric-api-0.92.2+1.11.8+1.20.1
- 3.0.0-beta.5+1.21

**Comment by Su5eD** [comment] 2024-07-16 07:15
Duplicate of #1001

**Closed by Su5eD** 2024-07-16 07:15 UTC
Labels: compat
