### ISSUE TITLE
All fragments and blocks from the embeddium and immersive portal mods are not displayed

### ISSUE THREAD

**Issue by Trojankill** [Sinytra/Connector#949] opened 2024-03-29 10:28 UTC
### Minecraft version

1.20.1

### Describe the bug

I enter the world and all chunks are not rendered

### Steps to reproduce

1.Log in to Minecraft
2.Enter any world
3.
...

### Additional context

versions of mods:
Force 47.2.21
embeddium 0.2.10
immersive portal 3.3.3

**Comment by Su5eD** [comment] 2024-03-29 19:21
Duplicate of #665. When using embeddium alongside Immersive Portals, you'll need to alias it as `sodium` to activate immptl's builtin integration code. See the [documentation](https://sinytra.org/docs/connector/configuration#global-mod-aliases) for an explanation.

**Closed by Su5eD** 2024-03-29 19:21 UTC
Labels: bug
