### ISSUE TITLE
Immersive Portal mod is no longer compatible with sinystra connector

### ISSUE THREAD

**Issue by agent1243** [Sinytra/Connector#1388] opened 2024-09-03 00:11 UTC
### Mod Name

Immersive Portals

### Mod Homepage

https://modrinth.com/mod/immersiveportals

### Minecraft version

1.21.1

### Describe the bug

 in version 1.20.1 Neoforge, I used the immersive portal mod with the connector and it worked very well, but now in Neoforge 1.21.1, I used the latest version of sinystra connector and immersive portals and it simply crashed

### Steps to reproduce

1.download the connector mod and immersive portals together
2.open the Neoforge loading screen
3.crash the game
...

### Logs

[20:56:25] [main/INFO]: ModLauncher running: args [--username, agente123, --version, neoforge-21.1.31, --gameDir, C:\Users\chrys\AppData\Roaming\.minecrafneo, --assetsDir, C:\Users\chrys\AppData\Roaming\.minecraft\assets, --assetIndex, 17, --uuid, 110a9ad063a143cc9f1d73a94949b7eb, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, NzY5MDg3YzYtNzBmNi00YmEyLWFhZjItNmM4YzIwODI2NzYy, --xuid, 2535464600291125, --userType, msa, --versionType, release, --fml.neoForgeVersion, 21.1.31, --fml.fmlVersion, 4.0.24, --fml.mcVersion, 1.21.1, --fml.neoFormVersion, 20240808.144430, --launchTarget, forgeclient] [20:56:25] [main/INFO]: JVM identified as Microsoft OpenJDK 64-Bit Server VM 21.0.3+9-LTS [20:56:25] [main/INFO]: ModLauncher 11.0.4+main.d2e20e43 starting: java version 21.0.3 by Microsoft; OS Windows 11 arch amd64 version 10.0 [20:56:25] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow [20:56:25] [main/INFO]: Trying GL version 4.6 [20:56:26] [main/INFO]: Requested GL version 4.6 got version 4.6 [20:56:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=union:/C:/Users/chrys/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.2+mixin.0.8.7/sponge-mixin-0.15.2+mixin.0.8.7.jar%23114!/ Service=ModLauncher Env=CLIENT [20:56:27] [pool-2-thread-1/INFO]: GL info: Intel(R) UHD Graphics 730 GL version 4.6.0 - Build 32.0.101.5972, Intel [20:56:27] [main/INFO]: Found mod file "client-1.21.1-20240808.144430-srg.jar" [locator: production client provider +net.neoforged:neoforge:21.1.31:client] [20:56:27] [main/INFO]: Found mod file "neoforge-21.1.31-universal.jar" [locator: PathBasedLocator[name=neoforge, paths=[C:\Users\chrys\AppData\Roaming\.minecraft\libraries\net\neoforged\neoforge\21.1.31\neoforge-21.1.31-universal.jar]], reader: mod manifest] [20:56:27] [main/INFO]: Found library file "~nonexistent" [locator: org.sinytra.connector.locator.ConnectorEarlyLocatorBootstrap@aed0151] [20:56:27] [main/INFO]: Found mod file "ConnectorExtras-1.12.1+1.21.1.jar" [locator: {mods folder locator at C:\Users\chrys\AppData\Roaming\.minecrafneo\mods}, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar" [locator: {mods folder locator at C:\Users\chrys\AppData\Roaming\.minecrafneo\mods}, reader: mod manifest] [20:56:27] [main/WARN]: Skipping jar. File mods\immersive-portals-6.0.1-mc1.21.1-fabric.jar is a Fabric mod and cannot be loaded [20:56:27] [main/WARN]: Skipping jar. File mods\modmenu-11.0.1.jar is a Fabric mod and cannot be loaded [20:56:27] [main/INFO]: Found 53 dependencies adding them to mods collection [20:56:27] [main/INFO]: Found mod file "fabric-transfer-api-v1-5.1.16+7f12564f19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-renderer-api-v1-3.4.0+acb05a3919.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "kubejs-bridge-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-item-api-v1-11.0.0+f56196c219.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-model-loading-api-v1-2.0.0+a6e994cd19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "modmenu-bridge-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-rendering-fluids-v1-3.1.6+857185bc19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "pehkui-bridge-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-screen-handler-api-v1-1.3.86+8dbc56dd19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-resource-loader-v0-1.3.0+bcae32ce19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-rendering-v1-5.0.5+2df007aa19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found gamelibrary file "mixinextras-neoforge-0.4.1.jar" [parent: neoforge-21.1.31-universal.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-renderer-indigo-1.7.0+acb05a3919.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-convention-tags-v1-2.0.19+7f945d5b19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-command-api-v2-2.2.28+36d727be19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-convention-tags-v2-2.5.0+ae4389fe19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-block-view-api-v2-1.0.10+9afaaf8c19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-data-attachment-api-v1-1.1.27+d82d50ba19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "rei-bridge-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-screen-api-v1-2.0.24+79a4c2b019.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "energy-bridge-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-particles-v1-4.0.2+824f924c19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-content-registries-v0-8.0.16+0a0c14ff19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "terrablender-bridge-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-transitive-access-wideners-v1-6.1.0+0df3143b19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-game-rule-api-v1-1.0.53+36d727be19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-api-base-0.4.42+d1308ded19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-api-lookup-api-v1-1.6.68+c21168c319.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-blockrenderlayer-v1-1.1.52+b089b4bd19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found library file "extras-utils-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-block-api-v1-1.0.22+a6e994cd19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "jei-bridge-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-resource-conditions-api-v1-4.3.0+ea90ec3c19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-item-group-api-v1-4.1.4+262bc2d219.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-gametest-api-v1-2.0.4+29f188ce19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-biome-api-v1-13.0.29+1e62d33c19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-entity-events-v1-1.6.12+0a0c14ff19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-registry-sync-v0-5.1.2+0c9b5b5419.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found library file "forgified-fabric-loader-2.5.29+0.16.0+1.21-full.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-recipe-api-v1-5.0.12+c653ba0e19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-object-builder-api-v1-15.2.0+9815f61f19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-loot-api-v2-3.0.14+a3ee712d19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-loot-api-v3-1.0.2+333dfad919.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-rendering-data-attachment-v1-0.3.48+73761d2e19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-networking-api-v1-4.2.2+a92978fd19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-sound-api-v1-1.0.23+d80d32ac19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-message-api-v1-6.0.13+e053909619.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "emi-bridge-1.12.1+1.21.1.jar" [parent: ConnectorExtras-1.12.1+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-lifecycle-events-v1-2.3.12+88bf4f7f19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-data-generation-api-v1-20.2.16+ed29d49b19.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-events-interaction-v0-0.7.12+7b71cc1619.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-key-binding-api-v1-1.0.47+62cc7ce119.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:27] [main/INFO]: Found mod file "fabric-client-tags-api-v1-1.1.15+e053909619.jar" [parent: forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar, locator: jarinjar, reader: mod manifest] [20:56:28] [main/INFO]: Dependency resolution found 5 candidates to load [20:56:35] [main/INFO]: Found mod file "immersive-portals-6.0.1-mc1.21.1-fabric$cloth-config-fabric-15.0.130-fabric$basic-math-0.6.1_mapped_moj_1.21.1.jar" [locator: org.sinytra.connector.locator.ConnectorLocator@c68a5f8] [20:56:35] [main/INFO]: Found mod file "immersive-portals-6.0.1-mc1.21.1-fabric$cloth-config-fabric-15.0.130-fabric_mapped_moj_1.21.1.jar" [locator: org.sinytra.connector.locator.ConnectorLocator@c68a5f8] [20:56:35] [main/INFO]: Found mod file "immersive-portals-6.0.1-mc1.21.1-fabric$DimLib-v1.1.0-mc1.21.1_mapped_moj_1.21.1.jar" [locator: org.sinytra.connector.locator.ConnectorLocator@c68a5f8] [20:56:35] [main/INFO]: Found mod file "immersive-portals-6.0.1-mc1.21.1-fabric_mapped_moj_1.21.1.jar" [locator: org.sinytra.connector.locator.ConnectorLocator@c68a5f8] [20:56:35] [main/INFO]: Found mod file "immersive-portals-6.0.1-mc1.21.1-fabric$DimLib-v1.1.0-mc1.21.1$midnightlib-1.5.7-fabric_mapped_moj_1.21.1.jar" [locator: org.sinytra.connector.locator.ConnectorLocator@c68a5f8] [20:56:36] [main/INFO]: Found 2 dependencies adding them to mods collection [20:56:36] [main/INFO]: Found mod file "org.sinytra.connector-2.0.0-beta.2+1.21.1-mod.jar" [parent: , locator: org.sinytra.connector.locator.ConnectorLocator@c68a5f8, reader: mod manifest] [20:56:36] [main/INFO]: Found gamelibrary file "runtime-1.0.0+1.21.1.jar" [parent: , locator: org.sinytra.connector.locator.ConnectorLocator@c68a5f8, reader: mod manifest] [20:56:36] [main/INFO]: Successfully made module authlib transformable [20:56:36] [main/INFO]: Loading coremod script-engine for [neoforge] [20:56:37] [main/INFO]: Compatibility level set to JAVA_17 [20:56:37] [main/INFO]: Compatibility level set to JAVA_21 [20:56:37] [main/INFO]: Launching target 'forgeclient' with arguments [--version, neoforge-21.1.31, --gameDir, C:\Users\chrys\AppData\Roaming\.minecrafneo, --assetsDir, C:\Users\chrys\AppData\Roaming\.minecraft\assets, --uuid, 110a9ad063a143cc9f1d73a94949b7eb, --username, agente123, --assetIndex, 17, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, NzY5MDg3YzYtNzBmNi00YmEyLWFhZjItNmM4YzIwODI2NzYy, --xuid, 2535464600291125, --userType, msa, --versionType, release] [20:56:37] [main/WARN]: Reference map '' for adapter.init.mixins.json could not be read. If this is a development environment you can ignore this message [20:56:37] [main/WARN]: Error loading class: net/fabricmc/fabric/impl/networking/client/ClientPlayNetworkAddon (java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon) [20:56:37] [main/WARN]: @Mixin target net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon was not found imm_ptl_fabric.mixins.json:client.MixinFabricClientPlayNetworkAddon from mod immersive_portals [20:56:38] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1). [02set.2024 20:56:40.406] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 229 Datafixer optimizations took 425 milliseconds [02set.2024 20:56:45.857] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/chrys/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.21.1-20240808.144430/client-1.21.1-20240808.144430-srg.jar%23186!/assets/.mcassetsroot' uses unexpected schema [02set.2024 20:56:45.858] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/chrys/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.21.1-20240808.144430/client-1.21.1-20240808.144430-srg.jar%23186!/data/.mcassetsroot' uses unexpected schema [02set.2024 20:56:45.927] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD] [02set.2024 20:56:45.949] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: agente123 [02set.2024 20:56:46.118] [Render thread/INFO] [iPortal/]: Loading Immersive Portals config [02set.2024 20:56:46.131] [Render thread/INFO] [iPortal/]: iPortal Config Applied [02set.2024 20:56:46.131] [Render thread/INFO] [iPortal/]: Immersive Portals Mod Initializing [02set.2024 20:56:46.205] [Render thread/INFO] [qouteall.imm_ptl.core.network.ImmPtlNetworkConfig/]: Immersive Portals Core version 6.0.1 [02set.2024 20:56:46.550] [Render thread/INFO] [iPortal/]: Dimensional Threading is not present [02set.2024 20:56:46.550] [Render thread/INFO] [iPortal/]: Gravity API is not present [02set.2024 20:56:46.561] [Render thread/INFO] [qouteall.dimlib.DimLibEntry/]: DimLib initializing [02set.2024 20:56:46.858] [Render thread/INFO] [iPortal/]: Sodium is not present [02set.2024 20:56:46.858] [Render thread/INFO] [iPortal/]: Iris is not present [02set.2024 20:56:47.135] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.3+5 [02set.2024 20:56:47.156] [Worker-Main-1/INFO] [qouteall.imm_ptl.core.compat.IPModInfoChecking/]: iPortal mod info fetched [02set.2024 20:56:47.435] [modloading-worker-0/INFO] [net.neoforged.neoforge.common.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 21.1.31, for MC 1.21.1 [02set.2024 20:56:47.454] [modloading-worker-0/INFO] [net.fabricmc.fabric.impl.client.indigo.Indigo/]: [Indigo] Registering Indigo renderer! [02set.2024 20:56:47.455] [modloading-worker-0/INFO] [net.fabricmc.fabric.impl.client.indigo.Indigo/]: [Indigo] Compatibility mode enabled. [02set.2024 20:56:47.456] [modloading-worker-0/INFO] [dev.su5ed.sinytra.connectorextras.terrablenderbridge.TerraBlenderBridge/]: Injecting TerraBlender API classes [02set.2024 20:56:47.458] [modloading-worker-0/WARN] [dev.su5ed.sinytra.connectorextras.util.HackyModuleInjector/]: Module terrablender is not present, skipping class injection [02set.2024 20:56:48.280] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 1befa918-32b8-4387-8a0d-c4b6b6fec43e [02set.2024 20:56:48.285] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 971d0710-3786-4f00-9e2a-4c3f1dd553c1

**Comment by Klevente12** [comment] 2024-09-03 00:11
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by maher-nakesh** [comment] 2024-09-03 00:11
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by agent1243** [comment] 2024-09-03 00:14
> tente isto https://bit.ly/4e4zLlq selecione o compilador desejado no instalador

the link you sent me seems to be blocked

**Comment by Su5eD** [comment] 2024-09-22 16:13
Duplicate of #564

**Closed as not planned by Su5eD** 2024-09-22 16:13 UTC
Labels: duplicate
