### ISSUE TITLE
ultracraft mod crash with zeta mod

### ISSUE THREAD

**Issue by oof100200** [Sinytra/Connector#979] opened 2024-04-06 06:56 UTC
### Mod Name

zeta ultracraft

### Mod Homepage

https://modrinth.com/mod/zeta/version/1.20.1-1.0-14  https://modrinth.com/mod/absolute-ultracraft/version/1.20.1-2.1.0

### Minecraft version

1.20.1

### Describe the bug

game crashed when loading world

### Steps to reproduce

beta41 dev

### Logs

https://pastebin.com/SJTVTQHF

**Comment by Su5eD** [comment] 2024-04-06 10:45
Duplicate of #957

**Closed by Su5eD** 2024-04-06 10:45 UTC
Labels: compat

**Comment by oof100200** [comment] 2024-04-06 16:13
> #957的重复[](https://github.com/Sinytra/Connector/issues/957)

This is not the same crash issue, please bother to take a look.
https://pastebin.com/FPndCL9U

**Comment by Su5eD** [comment] 2024-04-06 16:24
Yes I have, and I've tested ultracraft with zeta on the latest version of connector. It works fine. You log also mentions unrelated mods such as oculus, which might be the cause.

**Comment by oof100200** [comment] 2024-04-06 16:25
> 是的，我有，并且我已经在最新版本的连接器上使用 zeta 测试了 ultracraft。效果很好。您的日志还提到了不相关的模组，例如 oculus，这可能是原因。
thanks. i will test it.

**Comment by oof100200** [comment] 2024-04-06 16:45
> Yes I have, and I've tested ultracraft with zeta on the latest version of connector. It works fine. You log also mentions unrelated mods such as oculus, which might be the cause.

it works. thanks 4 the help.
