### ISSUE TITLE
Better Nether Fail to Load Dedicated Server

### ISSUE THREAD

**Issue by PneumaticPiston** [Sinytra/Connector#912] opened 2024-03-16 23:33 UTC
### Mod Name

Better Nether

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/betternether

### Minecraft version

1.20.1

### Describe the bug

Works on singleplayer worlds but does crashes when starting a multiplayer server

### Steps to reproduce

1. Download the latest version, as of this bug report, of Better Nether and Sinytra Connector
2. Run a forge dedicated server
3. The server will fail to load
...

### Logs

https://gist.github.com/PneumaticPiston/33dc966d18579dddc6451c050545ac9d

**Comment by liangmoe** [comment] 2024-03-17 04:00
This was fixed on devs version though, you can try devs version or wait for the beta 40 release

**Comment by Su5eD** [comment] 2024-03-17 09:43
Duplicate of #904

**Closed by Su5eD** 2024-03-17 09:43 UTC
Labels: compat
