### ISSUE TITLE
NeepMeat Incompatible (Geckolib issue?)

### ISSUE THREAD

**Issue by aking4125** [Sinytra/Connector#1010] opened 2024-04-16 01:33 UTC
### Mod Name

NeepMeat

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/neepmeat

### Minecraft version

1.20.1

### Describe the bug

Game crashes upon adding to pack

### Steps to reproduce

Added the mod to this pack to see if it works and it crashes. However, it seems to work with Connector and Geckolib (Fabric). There seems to be some issue when using the Forge version of Geckolib along side Fabric. Only using the Fabric version and my entire pack crashes requesting the Forge version. Idk its honestly too confusing to me.

### Logs

https://gist.github.com/aking4125/db2964878c596cff001ae355089a7b6b

**Comment by RoomAlex68** [comment] 2024-04-16 01:39
Use Geckolib Fabric. Forge Version of Geckolib is incompatible with most Geckolib Fabric mods due to not having a multiloader system like other mods have.

**Comment by aking4125** [comment] 2024-04-16 01:41
Using the Fabric version breaks the modpack completely. Causing random crashes when it loads models or mods that requires the forge version.

**Comment by RoomAlex68** [comment] 2024-04-16 03:01
Is there a specific mod that's causing the crash?

**Comment by Su5eD** [comment] 2024-04-16 05:59
Duplicate of #231

**Closed by Su5eD** 2024-04-16 05:59 UTC
Labels: compat
