### ISSUE TITLE
ReplayMod crashes with forge 47.1.3

### ISSUE THREAD

**Issue by user2949** [Sinytra/Connector#118] opened 2023-08-27 01:45 UTC
### Mod Name

ReplayMod

### Mod Homepage

https://www.replaymod.com/download/

### Describe the bug

ReplayMod doesn't work with the latest version of the mod using Sinytra Connector and Forgified Fabric API

### Steps to reproduce

1. Launch Minecraft Launcher
2. Install Forgified Fabric API and Sinytra Connector and also Replay Mod
3. Launch the game
...

### Logs

https://gist.github.com/user2949/1ada5d948736c87a6163f3026af48e5a

**Comment by Su5eD** [comment] 2023-08-27 07:43
Duplicate of #94

**Closed by Su5eD** 2023-08-27 07:43 UTC
Labels: compat
