### ISSUE TITLE
Can not run with Carpet

### ISSUE THREAD

**Issue by zlink2010** [Sinytra/Connector#1344] opened 2024-08-19 02:48 UTC
### Mod Name

Carpet

### Mod Homepage

https://modrinth.com/mod/carpet

### Minecraft version

1.21.1

### Describe the bug

The farbic loader:The mod "carpet" Injection Failed

### Logs

https://gist.github.com/zlink2010/6a88cf7d7be6323521da4e4fd0feb7c9

**Comment by Su5eD** [comment] 2024-08-19 09:47
Duplicate of #296

**Closed as not planned by Su5eD** 2024-08-19 09:47 UTC
Labels: duplicate
