### ISSUE TITLE
Viafabric Plus not working

### ISSUE THREAD

**Issue by JS-Pilot** [Sinytra/Connector#1395] opened 2024-09-06 20:22 UTC
### Mod Name

Viafabric Plus

### Mod Homepage

https://modrinth.com/mod/viafabricplus

### Minecraft version

1.21.1

### Describe the bug

Minecraft crashes on "Loading bootstrap resources"

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/JS-Pilot/7ec08469375f8cbec6af3d6a998632be#file-debug-log

### Additional context

I am using ATlauncher

**Comment by Su5eD** [comment] 2024-09-22 16:10
Duplicate of #1209

**Closed as not planned by Su5eD** 2024-09-22 16:10 UTC
Labels: duplicate

**Comment by zaqrsuig** [comment] 2025-06-07 02:13
i have the same problom😒
