### ISSUE TITLE
PlayerEx: Director's Cut Incompatibility

### ISSUE THREAD

**Issue by Nol-IsntUse** [Sinytra/Connector#1019] opened 2024-04-20 23:31 UTC
### Mod Name

PlayerEx: Director's Cut

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/playerex-directors-cut

### Minecraft version

1.20.1

### Describe the bug

Crashes when pressing singleplayer

### Steps to reproduce

1. Download the mod and its dependencies
2. Launch the game
3. Click "singleplayer"
4. Crashes
...

### Logs

https://pastebin.com/WDqX86de

### Additional context

No other mods were installed
```[tasklist]
### Tasks
```

**Comment by Su5eD** [comment] 2024-04-21 08:44
Duplicate of #699

**Closed by Su5eD** 2024-04-21 08:44 UTC
Labels: compat
