### ISSUE TITLE
Autoslabs

### ISSUE THREAD

**Issue by Its-Just-Luci** [Sinytra/Connector#728] opened 2024-01-19 03:41 UTC
### Mod Name

autoslabs

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/autoslabs

### Minecraft version

1.20.1

### Describe the bug

game won't boot

### Logs

https://gist.github.com/Its-Just-Luci/cc80d497419046dc7e6cc362ecbf1cd9

**Comment by Su5eD** [comment] 2024-01-19 08:28
Duplicate of #598

**Closed by Su5eD** 2024-01-19 08:28 UTC
Labels: compat
