### ISSUE TITLE
Crash with Andromeda and the latest Connector

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [Sinytra/Connector#1035] opened 2024-04-25 03:18 UTC
### Mod Name

Andromeda

### Mod Homepage

https://modrinth.com/mod/andromeda

### Minecraft version

1.20.1

### Describe the bug

The game crashes on startup with exit code 2

### Steps to reproduce

1. Install connector, forgified api and andromeda
2. Launch the game
3. See how your game crashes lol
...

### Logs

debug log: https://mclo.gs/LS4xAYn

### Additional context

I've only attached the debug log because the game doesn't generate a crash log and the latest log is not showing anything important.

**Comment by Su5eD** [comment] 2024-04-25 06:39
Duplicate of #1021

**Closed by Su5eD** 2024-04-25 06:39 UTC
Labels: compat
