### ISSUE TITLE
Crawl (Fabric) + Zoomify crash

### ISSUE THREAD

**Issue by marian-mdn12** [Sinytra/Connector#911] opened 2024-03-16 22:28 UTC
### Mod Name

Crawl (Fabric) + Zoomify

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/crawl - https://www.curseforge.com/minecraft/mc-mods/zoomify

### Minecraft version

1.20.1

### Describe the bug

Having Crawl (Fabric), Zoomify (along with YACL and Fabric Language Kotlin) and Forgified Fabric API, Sinytra Connector and Connector Extras crashes the game when creating a world.

### Steps to reproduce

1. Open the modpack with all 7 mentioned mods included;
2. Create a world.

### Logs

https://mclo.gs/Id9p6bk

### Additional context

It appears that any other combination of the mods works just fine, only when all of them are together the game crashes.
I'll show the combinations I tried and refer to the mods as follows:
a. Crawl (Fabric);
b. Zoomify (along with YACL and Fabric Language Kotlin);
c. Forgified Fabric API, Sinytra Connector and Connector Extras.

a + b = https://mclo.gs/BPnXsMQ `Fabric`
a + c = https://mclo.gs/xxG1LGv `Forge`
b + c = https://mclo.gs/KvS66ul `Forge`
a + b + c  = https://mclo.gs/Id9p6bk (The log mentioned in the `logs` field) `Forge`

**Comment by Su5eD** [comment] 2024-03-17 19:05
Duplicate of #913, will be fixed in the next release

**Closed by Su5eD** 2024-03-17 19:05 UTC
Labels: compat
