### ISSUE TITLE
BetterNether messes up BOP/RU nether biomes

### ISSUE THREAD

**Issue by SPSick** [Sinytra/Connector#535] opened 2023-11-25 15:55 UTC
### Describe the bug

BOP/RU nether's biomes dont have the ground block they are supposed to have and sometimes some extra blocks added. 

### Steps to reproduce

1.Create a world with BetterNether, BCLib, Biomes O' Plenty (or Regions Unexplored)
2.Travel to the Nether
3.Find/Locate a BOP/RU biome and you will see what I mean by the fact it looks extremely weird and messy.
...

**Comment by Su5eD** [comment] 2023-11-25 16:08
Duplicate of https://github.com/quiqueck/BCLib/issues/75

**Closed by Su5eD** 2023-11-25 16:08 UTC
Labels: needs info
