### ISSUE TITLE
Incompatible with Marium's Soulslike weaponry and Celestisynth

### ISSUE THREAD

**Issue by N3WtrAllX** [Sinytra/Connector#1214] opened 2024-07-04 23:08 UTC
### Mod Name

Marium's Soulslike weaponry & Celestisynth 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry

### Minecraft version

1.20.1

### Describe the bug

Using both of these mods (Celestisynth & Marium's Soulslike weaponry) at the same time the game crashes. Using these mods separately they work

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/5kG1NvNh

### Additional context

Celestisynth mod homepage: https://www.curseforge.com/minecraft/mc-mods/celestisynth

**Comment by Su5eD** [comment] 2024-07-26 13:18
Duplicate of #231

**Closed by Su5eD** 2024-07-26 13:18 UTC
Labels: compat
