### ISSUE TITLE
MoreCulling Incompatible Mod / Crash

### ISSUE THREAD

**Issue by ProStoKrut123** [Sinytra/Connector#875] opened 2024-03-02 15:13 UTC
### Mod Name

MoreCulling

### Mod Homepage

https://modrinth.com/mod/moreculling

### Minecraft version

1.20.1

### Describe the bug

The MoreCulling mod is not supported, which is surprising given its popularity. Is there any information on whether this mod will be supported in the future, or am I missing something?

### Steps to reproduce

The More Culling mod requires the Cloth Config API library. The Modrinth site has both the cloth and forge versions of this library, but the More Culling mod itself only has the cloth version. I don't really know how the Sinytra Connector works, so I tried running it with both libraries. In both cases Minecraft crashed, both crash logs with different libraries attached.
Here's the crash log when using the forge version's Cloth Config API dependency:
[crash-2024-03-02_18.08.40-client-forge.txt](https://github.com/Sinytra/Connector/files/14469811/crash-2024-03-02_18.08.40-client-forge.txt)
Here's the crash log when using the fabric version's Cloth Config API dependency:
[crash-2024-03-02_18.07.01-client-fabric.txt](https://github.com/Sinytra/Connector/files/14469813/crash-2024-03-02_18.07.01-client-fabric.txt)

### Logs

[<script src="https://gist.github.com/ProStoKrut123/5fb0d51c3e14d8e16fe208755930b111.js"></script>](https://gist.github.com/ProStoKrut123/5fb0d51c3e14d8e16fe208755930b111)

### Additional context

Mod List:
1.Connector-1.0.0-beta.37+1.20.1
2.ConnectorExtras-1.9.3+1.20.1
3.fabric-api-0.92.0+1.11.3+1.20.1 
4.moreculling-1.20.4-0.22.1
5.cloth-config-11.1.118-forge
5.cloth-config-11.1.118-fabric
Forge version 47.2.4

**Comment by Su5eD** [comment] 2024-03-02 15:23
Duplicate of #167

**Closed by Su5eD** 2024-03-02 15:23 UTC
Labels: compat
