### ISSUE TITLE
Neoforge 1.21.1 Dedicated Server always crash

### ISSUE THREAD

**Issue by zFERDQFREZrzfq** [Sinytra/Connector#1428] opened 2024-09-20 19:01 UTC
### Minecraft version

1.21.1

### Describe the bug

Can't start a dedicated Neoforge 1.21.1 server with Connector installed

### Steps to reproduce

1. Install a Neoforge server
2. Add Connector
3. Start the server

### Logs

See below

### Additional context

This happens only on DEDICATED_SERVER, probably because of some CLIENT mixins are trying to lod.
There is no issue when running on self-hosted environment.
Full crash log :
```
[18:51:20.421] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.neoForgeVersion, 21.1.57, --fml.fmlVersion, 4.0.24, --fml.mcVersion, 1.21.1, --fml.neoFormVersion, 20240808.144430, nogui]
[18:51:20.426] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 11.0.4+main.d2e20e43 starting: java version 21 by Oracle Corporation; OS Linux arch aarch64 version 6.8.0-1013-oracle
[18:51:20.614] [main/INFO] [loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[18:51:20.717] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=union:/home/mc/mc/srvs/MI/libraries/net/fabricmc/sponge-mixin/0.15.2+mixin.0.8.7/sponge-mixin-0.15.2+mixin.0.8.7.jar%2375!/ Service=ModLauncher Env=SERVER
[18:51:20.925] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "server-1.21.1-20240808.144430-srg.jar" [locator: production server provider +net.neoforged:neoforge:21.1.57:server]
[18:51:20.945] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "neoforge-21.1.57-universal.jar" [locator: PathBasedLocator[name=neoforge, paths=[libraries/net/neoforged/neoforge/21.1.57/neoforge-21.1.57-universal.jar]], reader: mod manifest]
[18:51:20.949] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found library file "~nonexistent" [locator: org.sinytra.connector.locator.ConnectorEarlyLocatorBootstrap@4263b080]
[18:51:21.068] [main/INFO] [loading.moddiscovery.locators.JarInJarDependencyLocator/]: Found 2 dependencies adding them to mods collection
[18:51:21.069] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found library file "neoforge-coremods-21.1.57.jar" [parent: neoforge-21.1.57-universal.jar, locator: jarinjar, reader: mod manifest]
[18:51:21.069] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found gamelibrary file "mixinextras-neoforge-0.4.1.jar" [parent: neoforge-21.1.57-universal.jar, locator: jarinjar, reader: mod manifest]
[18:51:21.246] [main/INFO] [locator.DependencyResolver/]: Dependency resolution found 0 candidates to load
[18:51:21.351] [main/INFO] [loading.moddiscovery.locators.JarInJarDependencyLocator/]: Found 2 dependencies adding them to mods collection
[18:51:21.351] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found mod file "org.sinytra.connector-2.0.0-beta.2+1.21.1-mod.jar" [parent: , locator: org.sinytra.connector.locator.ConnectorLocator@76b74e9c, reader: mod manifest]
[18:51:21.351] [main/INFO] [loading.moddiscovery.ModDiscoverer/SCAN]: Found gamelibrary file "runtime-1.0.0+1.21.1.jar" [parent: , locator: org.sinytra.connector.locator.ConnectorLocator@76b74e9c, reader: mod manifest]
[18:51:21.605] [main/INFO] [service.hacks.ModuleLayerMigrator/]: Successfully made module authlib transformable
[18:51:21.816] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[18:51:21.866] [main/INFO] [LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[18:51:22.095] [main/WARN] [mixin/]: Reference map '' for adapter.init.mixins.json could not be read. If this is a development environment you can ignore this message
[18:51:22.223] [main/ERROR] [common.asm.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/RecipeBookCategories for invalid dist DEDICATED_SERVER
[18:51:22.234] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/RecipeBookCategories (java.lang.RuntimeException: Attempted to load class net/minecraft/client/RecipeBookCategories for invalid dist DEDICATED_SERVER)
[18:51:22.235] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.RecipeBookCategories was not found connector.mixins.json:recipebook.RecipeBookCategoriesAccessor from mod connector
[18:51:22.237] [main/ERROR] [common.asm.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/RecipeBookCategories for invalid dist DEDICATED_SERVER
[18:51:22.238] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/RecipeBookCategories (java.lang.RuntimeException: Attempted to load class net/minecraft/client/RecipeBookCategories for invalid dist DEDICATED_SERVER)
[18:51:22.238] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.RecipeBookCategories was not found connector.mixins.json:recipebook.RecipeBookCategoriesMixin from mod connector
[18:51:22.254] [main/ERROR] [common.asm.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/ItemBlockRenderTypes for invalid dist DEDICATED_SERVER
[18:51:22.256] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/ItemBlockRenderTypes (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/ItemBlockRenderTypes for invalid dist DEDICATED_SERVER)
[18:51:22.256] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.ItemBlockRenderTypes was not found connector.mixins.json:registries.ItemBlockRenderTypesMixin from mod connector
[18:51:22] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[18:51:29] [modloading-worker-0/INFO] [ne.ne.ne.co.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 21.1.57, for MC 1.21.1
[18:51:29] [main/FATAL] [ne.ne.fm.ModLoader/LOADING]: Failed to wait for future Registry initialization, 1 errors found
[18:51:29] [main/ERROR] [minecraft/CrashReport]: Negative index in crash report handler (0/25)
[18:51:29] [main/FATAL] [ne.ne.ne.co.NeoForgeMod/]: Preparing crash report with UUID 8e18cc6b-9e45-4963-9bbe-029a07a2c2d5
[18:51:29] [main/FATAL] [ne.ne.ne.se.lo.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2024-09-20_18.51.29-fml.txt
[18:51:29] [main/FATAL] [ne.ne.ne.co.NeoForgeMod/]: Preparing crash report with UUID cb499635-9bd5-4b74-b022-239aa27385b2
---- Minecraft Crash Report ----

// Hi. I'm Connector, and I'm a crashaholic
=========================
SINYTRA CONNECTOR IS PRESENT!
Please verify issues are not caused by Connector before reporting them to mod authors.
If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.
=========================


// Who set us up the TNT?

Time: 2024-09-20 18:51:29
Description: Mod loading failures have occurred; consult the issue messages for more details

net.neoforged.neoforge.logging.CrashReportExtender$ModLoadingCrashException: Mod loading has failed


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.RegistryDataLoader.handler$zzo000$connector$postInitLast(RegistryDataLoader.java:522) ~[?:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:connector.mixins.json:registries.RegistryDataLoaderMixin from mod connector,pl:mixin:A,pl:connector_pre_launch:A}
-- Mod loading issue --
Details:
        Caused by 0: java.lang.ExceptionInInitializerError
                at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.registries.DataPackRegistriesHooks.<clinit>(DataPackRegistriesHooks.java:25) ~[neoforge-21.1.57-universal.jar%23122!/:?] {re:mixin,re:classloading,pl:mixin:APP:connector.mixins.json:registries.DataPackRegistriesHooksAccessor from mod connector,pl:mixin:A}
                at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.registries.DataPackRegistryEvent$NewRegistry.process(DataPackRegistryEvent.java:79) ~[neoforge-21.1.57-universal.jar%23122!/:?] {re:classloading}
                at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.registries.RegistryManager.postNewRegistryEvent(RegistryManager.java:87) ~[neoforge-21.1.57-universal.jar%23122!/:?] {re:classloading}
                at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:52) ~[neoforge-21.1.57-universal.jar%23122!/:?] {re:classloading}
                at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1848) ~[?:?] {}
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
                at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?] {}

        Mod file: <No mod information provided>
        Failure message: An uncaught parallel processing error has occurred.
                java.lang.ExceptionInInitializerError: null
        Mod version: <No mod information provided>
        Mod issues URL: <No issues URL found>
        Exception message: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "net.neoforged.neoforge.registries.DataPackRegistriesHooks.getDataPackRegistries()" is null
Stacktrace:
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.RegistryDataLoader.handler$zzo000$connector$postInitLast(RegistryDataLoader.java:522) ~[server-1.21.1-20240808.144430-srg.jar%23121!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:connector.mixins.json:registries.RegistryDataLoaderMixin from mod connector,pl:mixin:A,pl:connector_pre_launch:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.RegistryDataLoader.<clinit>(RegistryDataLoader.java:103) ~[server-1.21.1-20240808.144430-srg.jar%23121!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:connector.mixins.json:registries.RegistryDataLoaderMixin from mod connector,pl:mixin:A,pl:connector_pre_launch:A}
        at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.registries.DataPackRegistriesHooks.<clinit>(DataPackRegistriesHooks.java:25) ~[neoforge-21.1.57-universal.jar%23122!/:?] {re:mixin,re:classloading,pl:mixin:APP:connector.mixins.json:registries.DataPackRegistriesHooksAccessor from mod connector,pl:mixin:A}
        at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.registries.DataPackRegistryEvent$NewRegistry.process(DataPackRegistryEvent.java:79) ~[neoforge-21.1.57-universal.jar%23122!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.registries.RegistryManager.postNewRegistryEvent(RegistryManager.java:87) ~[neoforge-21.1.57-universal.jar%23122!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.1.57/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:52) ~[neoforge-21.1.57-universal.jar%23122!/:?] {re:classloading}
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1848) ~[?:?] {}
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?] {}


-- System Details --
Details:
        Minecraft Version: 1.21.1
        Minecraft Version ID: 1.21.1
        Operating System: Linux (aarch64) version 6.8.0-1013-oracle
        Java Version: 23, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 790811032 bytes (754 MiB) / 1040187392 bytes (992 MiB) up to 6308233216 bytes (6016 MiB)
        CPUs: 4
        Processor Vendor: ARM
        Processor Name:
        Identifier: ARM Family 8 Model 0xd0c Stepping r3p1
        Microarchitecture: unknown
        Frequency (GHz): -0.00
        Number of physical packages: 1
        Number of physical CPUs: 4
        Number of logical CPUs: 4
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MiB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MiB): 11989.56
        Virtual memory used (MiB): 2665.26
        Swap memory total (MiB): 0.00
        Swap memory used (MiB): 0.00
        Space in storage for jna.tmpdir (MiB): <path not set>
        Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
        Space in storage for io.netty.native.workdir (MiB): <path not set>
        Space in storage for java.io.tmpdir (MiB): available: 10040.79, total: 46041.01
        Space in storage for workdir (MiB): available: 10040.79, total: 46041.01
        JVM Flags: 6 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
        Sinytra Connector: 2.0.0-beta.2+1.21.1
                SINYTRA CONNECTOR IS PRESENT!
                Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker.
                Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues.
        ModLauncher: 11.0.4+main.d2e20e43
        ModLauncher launch target: forgeserver
        ModLauncher services:
                sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE
                loader-4.0.24.jar slf4jfixer PLUGINSERVICE
                loader-4.0.24.jar runtime_enum_extender PLUGINSERVICE
                at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE
                loader-4.0.24.jar runtimedistcleaner PLUGINSERVICE
                modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE
                modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE
                modlauncher-11.0.4.jar connector_loader TRANSFORMATIONSERVICE
        FML Language Providers:
                javafml@4.0
                lowcodefml@4.0
                minecraft@4.0
        Mod List:
                server-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: NOSIGNATURE
                org.sinytra.connector-2.0.0-beta.2+1.21.1-mod.jar |Sinytra Connector             |connector                     |2.0.0-beta.2+1.21.1 |Manifest: NOSIGNATURE
                neoforge-21.1.57-universal.jar                    |NeoForge                      |neoforge                      |21.1.57             |Manifest: NOSIGNATURE
        Crash Report UUID: cb499635-9bd5-4b74-b022-239aa27385b2
        FML: 4.0.24
        NeoForge: 21.1.57
```

**Comment by zFERDQFREZrzfq** [comment] 2024-09-20 19:10
Related : #1346, #1419

**Comment by Su5eD** [comment] 2024-09-21 19:03
Duplicate of #1346

**Closed as not planned by Su5eD** 2024-09-21 19:03 UTC
Labels: duplicate

**Comment by Rarity1** [comment] 2024-10-13 00:37
I assume its related to the fabric loader having an issue with java 23. Dropping to openjdk 21 fixes this issue for me. Idk why the devs said this is a duplicate its obviously not
