### ISSUE TITLE
Incompatibility with Key Binding Patch

### ISSUE THREAD

**Issue by AveragAr** [Sinytra/Connector#1316] opened 2024-08-10 19:10 UTC
### Mod Name

Key Binding Patch

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/key-binding-patch

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The game crashed upon trying to start up

### Steps to reproduce

1. 
2.
3.
...

### Logs

Crashlog: <script src="https://gist.github.com/AveragAr/6109cc7f7a4c796c816340354b3a8d57.js"></script> debug: <script src="https://gist.github.com/AveragAr/6bb4b9fe8debbed95bb589e2d95aa4cf.js"></script>

**Comment by Su5eD** [comment] 2024-08-10 19:21
Duplicate of #1250

**Closed as not planned by Su5eD** 2024-08-10 19:21 UTC
Labels: duplicate
