### ISSUE TITLE
Local NeoForge server crash during startup with any Fabric mod [1.21.1]

### ISSUE THREAD

**Issue by rafik131313** [Sinytra/Connector#1346] opened 2024-08-19 17:18 UTC
### Mod Name

Ping Wheel

### Mod Homepage

https://modrinth.com/mod/ping-wheel/version/EptlZW3F

### Minecraft version

1.21.1

### Describe the bug

Any Fabric mod causes the server to crash on startup. 

### Steps to reproduce

1. Download NeoForge installer from the official site. (used for example version 21.1.16)
2. Run the downloaded NeoForge installer and choose "Install server"
3.  Choose the empty folder on the disk
4. Run the run.bat file created during installation
5. Close the terminal, and change the EULA to true
6. Run the run.bat file again to start the server
7. Stop the server
8. Put in the mods folder jar files:
connector-2.0.0-beta.2+1.21.1-full
ConnectorExtras-1.12.1+1.21.1
forgified-fabric-api-0.102.0+2.0.12+1.21.1
Any Fabric mod compatible with 1.21.1 version, for example Ping Wheel/Terrestria
9. Run server again
10.  Expect crash with information of corrupted neoforge installation.

### Logs

https://gist.github.com/rafik131313/15b94f7098e94883df8c16bc328db6df and https://gist.github.com/rafik131313/4deaf3971c9459d71e978536d0854954

### Additional context

I would like to migrate my Fabric server with mods (just a few such as PingWheel) to NeoForge + Sinytra (1.21.1). The first thing I did was installing all the mods on a local client to check if they were compatible. The operation was successful. Next, I decided to install the NeoForge server locally to generate the necessary files, which would later be uploaded to the hosting service. I used the exact same versions of the mods and NeoForge. One of them was a Fabric mod (PingWheel), while the rest were NeoForge mods. Unfortunately, I noticed that adding the Fabric mod caused the server to crash on startup. To verify if the problem was with PingWheel, I replaced it with a mod that is officially supported, namely Terrestria, but with the same result. Changing the server version along with the add-ons to NeoForge 1.20.1 did not bring any changes.

**Comment by KewlSage** [comment] 2024-08-22 00:39
also having this problem with my testing bloom.host server

**Comment by rafik131313** [comment] 2024-08-22 07:20
I hope this will change soon :( I am checking for updates everyday 😥

**Comment by sisby-folk** [comment] 2024-08-24 14:38
can confirm FFAPI w/ connector is broken on dedicated servers. here's my sanity setup:

![image](https://github.com/user-attachments/assets/77337b40-003c-4242-924b-774674eedf92)

[Totem Anywhere](https://modrinth.com/mod/totem-anywhere) is the smallest mod i have or know, and doesn't require fapi to run.

https://mclo.gs/UHZVj3A for the above

I also tried with just totem + connector which crashed, but then discarded this when i realised connector alone also just crashes - i figure connector requiring ffapi outright is just the norm now.

From what i can tell, the underlying cause of this issue can create all kinds of red herring crash logs - I've seen "connector is not installed" unhelpful soft fails in singleplayer instances as well at times (specifically, when i have a fabric mod with its own missing dependency), so I guess they might be related?

**Comment by Bassote** [comment] 2024-08-27 04:36
I'm also having the same problem without any mods, just Connector and FFAPI, tried with NoEmotecraft and just with base Connector and FFAPI and both errors were the same, "Your NeoForge installation is corrupted", tried with different versions of NeoForge, reinstalling, and different folders and it didn't work.

**Comment by parmerinha99** [comment] 2024-09-07 00:36
It happened to me too. With any Fabric mod using the Connector

**Comment by Deveune250** [comment] 2024-09-07 01:24
I am not alone, which is reassuring.  I have exactly the same problem as you

**Comment by TDEnderP** [comment] 2024-09-07 05:08
Ok glad im not crazy and this is a general issue. Hope this can be resolved soon.

**Comment by rafik131313** [comment] 2024-09-13 09:43
FYI guys, the issue is known and "will be fix in the future" :)

![obraz_2024-09-13_114247248](https://github.com/user-attachments/assets/9e47e9c1-49b8-4c6b-b658-325697903f10)

**Comment by sisby-folk** [comment] 2024-09-13 09:46
@Su5eD mentioning you again because this will be miscategorized in triage (see above)

**Comment by coco875** [comment] 2024-09-13 10:25
I mention I am not a dev and the issue need to be open to be reference for other people who have the same issue

**Comment by deadca763** [comment] 2024-09-15 12:14
I also have this crash on neoforge server boot
Hope update come soon!

**Comment by sakurawald** [comment] 2024-09-29 08:57
Confirmed, sinytra-connector can't work in dedicated-server.

**Comment by Su5eD** [comment] 2024-09-29 09:10
Fixed by #1419

**Closed as completed by Su5eD** 2024-09-29 09:10 UTC
Labels: bug, compat, 1.21.x
