### ISSUE TITLE
Simple pipes (buildcraft pipes) incompat

### ISSUE THREAD

**Issue by awesomebossdj7** [Sinytra/Connector#1127] opened 2024-06-05 15:32 UTC
### Mod Name

Simple pipes

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/simplepipes

### Minecraft version

1.20.1

### Describe the bug

crash on startup / boot

### Steps to reproduce

1. download mod and connector
2. launch game
3. boom

### Logs

https://gist.github.com/awesomebossdj7/fbd27dfa24b636efa3722d9015855b31 (has both crash and log)

### Additional context

really cool mod, hope its fixable 🙏

**Comment by Su5eD** [comment] 2024-06-05 16:55
Duplicate of https://github.com/Sinytra/Connector/issues/478

**Closed by Su5eD** 2024-06-05 16:55 UTC
Labels: compat
