### ISSUE TITLE
1.20.1 replay mod incompatibility with latest sinytra version

### ISSUE THREAD

**Issue by KaratFeng** [Sinytra/Connector#770] opened 2024-01-25 17:22 UTC
### Mod Name

Replay Mod

### Mod Homepage

https://www.replaymod.com/download/

### Minecraft version

1.20.1

### Describe the bug

Using the latest version of Sinytra and Forgified fabric crash with replay mod, but not sinytra version "Connector-1.0.0-beta.25+1.20.1" and forgifed fabric "fabric-api-0.90.7+1.10.1+1.20.1"

### Steps to reproduce

1. Add replay mod 1.20.1 to your mods
2. instal the latest version of Sinytra and Forgified fabric
3. launch the game
4. Crash
...

### Logs

https://gist.github.com/KaratFeng/149f7c5454fa64ebd4a3249ecf5e3232

### Additional context

Like said earlier Connector-1.0.0-beta.25+1.20.1 and fabric-api-0.90.7+1.10.1+1.20.1 work

**Comment by Su5eD** [comment] 2024-01-25 19:07
Duplicate of #589

**Closed by Su5eD** 2024-01-25 19:07 UTC
Labels: compat
