### ISSUE TITLE
Wilderwild dosent work properly on 1.21 neoforge sinytra

### ISSUE THREAD

**Issue by YaeSlight** [Sinytra/Connector#1319] opened 2024-08-11 09:09 UTC
### Mod Name

wilderwild

### Mod Homepage

https://modrinth.com/mod/wilder-wild

### Minecraft version

1.21.1

### Describe the bug

using PCL luncher, with the crash "名为 wilderwild-2.4.8-mc-1.21_moj_1.21.jar 注入失败，导致游戏出错。”

### Steps to reproduce

1.im sure that i had installed the lastet version of sinytra connector and forgified fabric api.
2.adding the wilderwild mod to the mods folder.
3.game could not lunch and the crash report comes out.
...

### Logs

[https://gist.github.com/YaeSlight/90de085d4571da03affd8fb4a619632e](url)

**Comment by Su5eD** [comment] 2024-08-11 12:23
Duplicate of #1055

**Closed as not planned by Su5eD** 2024-08-11 12:23 UTC
Labels: duplicate
