### ISSUE TITLE
Universal Graves dropping trinkets when used with Connector

### ISSUE THREAD

**Issue by evanevanich** [Sinytra/Connector#1118] opened 2024-05-30 21:59 UTC
### Mod Name

universal graves

### Mod Homepage

https://modrinth.com/mod/universal-graves

### Minecraft version

1.20.1

### Describe the bug

If wearing trinkets (we're using trinkets from artifacts, which uses the curios API) on death the trinkets drop instead of going into the universal grave. I have created an issue with the graves mod dev and he said that as we are using sinytra (and because the issue isn't present when used in a modpack without sinytra) that I needed to bring the issue up here instead. The trinkets are supposed to be stored in the grave on death but this is not the case.

### Steps to reproduce

1. install sinytra's connector, universal graves (fabric version) and artifacts mod (forge version), equip artifacts into the trinket slots
2. die
3. upon returning to the grave, trinkets are on the floor as opposed to in the grave
...

### Logs

https://pastebin.com/xrSQTnc2

### Additional context

(pls note for the pastebin above line 2482 is the start of when I logged into a world to replicate the error, you'll see the grave is made but in-world the trinkets dropped on the floor)

We're using a multitude of other mods but I assume these are the relevant ones as the rest of the mods function as intended. I can provide the mod list upon request.

Equally, here is the link to the issue on the universal graves github: https://github.com/Patbox/UniversalGraves/issues/152

**Comment by Su5eD** [comment] 2024-05-31 06:58
Duplicate of #1117

**Closed by Su5eD** 2024-05-31 06:58 UTC
Labels: compat
