### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by DionSilver** [Sinytra/Connector#1123] opened 2024-06-01 07:08 UTC
### Mod Name

So Many Enchantments

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/so-many-enchantments

### Minecraft version

1.20.1

### Describe the bug

The mod crashes the launcher whenever I try to load it.

### Steps to reproduce

1.Launch the game
2.Wait for it to load
3.Launcher crashes
...

### Logs

exited. closed with exit code: 1 flush now

### Additional context

Context: The mod "so many enchantments" crashes whenever I try launch. It does have a dependentcy and that is Enchanted Lib. Though I have tried running the game with just Enchanted lib and it works perfectly, in addition to this i have around 130 mods and everything works just fine, this only happens when I try and run the game with so many enchantments, I have tried running the game with just so many enchantments too, just to make sure and it still crashes.

**Comment by Su5eD** [comment] 2024-06-01 09:23
Duplicate of #1122

**Closed by Su5eD** 2024-06-01 09:23 UTC
Labels: compat
