### ISSUE TITLE
Bewitchment forge 47.1.6+ not working

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#782] opened 2024-01-27 20:30 UTC
### Mod Name

Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Minecraft version

1.20.1

### Describe the bug

Game doesnt boot

### Steps to reproduce

Install
Launch on forge 47.1.6 or higher

### Logs

log https://gist.github.com/Tomat777/332084d72c23e683bd35a4fc4d8f0021

### Additional context

dev log https://gist.github.com/Tomat777/20365ac92d7afa54b85036595f2c3948
console output https://gist.github.com/Tomat777/8e62cc37e7584461918d3804d49e78fe
Game exits without crash log
Forge 47.1.3 boots normally but its old and doesnt launch a lot of mods

**Comment by Su5eD** [comment] 2024-01-27 20:32
Duplicate of #781

**Closed by Su5eD** 2024-01-27 20:32 UTC
Labels: compat
