### ISSUE TITLE
Using this with fabric Geckolib can make some items turn invisible

### ISSUE THREAD

**Issue by NEFFLEAFF** [Sinytra/Connector#198] opened 2023-09-05 22:12 UTC
### Describe the bug

Some forge modded items become invisible when using Connector

### Steps to reproduce

1.For example, get L_Ender's Cataclysm mod and Citadel, and a fabric Geckolib version
2.Launch the game
3.Join a world and open inventory, the Cataclysm's tab will be invisible along with some other items 
...

**Comment by tharrmeehan** [comment] 2023-09-06 16:39
duplicate of #123

**Comment by Su5eD** [comment] 2023-09-06 17:13
The issue comes down to Fabric geckolib overriding the vanilla ItemRenderer with its own system, which is not compatible with Forge's `IClientItemExtensions` interface. As a result, geckolib can never find the correct render for Forge items that use custom models and ends up skipping rendering altogether. Unfortunately, it is beyond our control.

The ideal solution would be for geckolib to use a multiloader layout with shared code so the loader-specific versions can be interchanged without causing any problems. They have, however, made the decision to maintain 2 independent versions for each loader, and they likely had reasons for it. It might be worth asking about their opinion on multiloader, but it's certainly something we can't force them to do if they don't want to.

**Comment by AzureDoom** [comment] 2023-09-08 06:04
> The issue comes down to Fabric geckolib overriding the vanilla ItemRenderer with its own system, which is not compatible with Forge's `IClientItemExtensions` interface. As a result, geckolib can never find the correct render for Forge items that use custom models and ends up skipping rendering altogether. Unfortunately, it is beyond our control.
> 
> The ideal solution would be for geckolib to use a multiloader layout with shared code so the loader-specific versions can be interchanged without causing any problems. They have, however, made the decision to maintain 2 independent versions for each loader, and they likely had reasons for it. It might be worth asking about their opinion on multiloader, but it's certainly something we can't force them to do if they don't want to.

TBH, a multiloader layout would be overkill for this, but they have plans for it at some point (I am not part of the Geckolib team anymore). 

I tested my fork for this issue, and it seems it doesn't have this issue since I do a different approach to that mixin. https://github.com/AzureDoom/AzureLib/blob/1.20/Fabric/src/main/java/mod/azure/azurelib/mixins/fabric/MixinItemRenderer.java

**Closed** 2023-10-13 19:12 UTC
Labels: compat
