### ISSUE TITLE
ULTRACRAFT server crash

### ISSUE THREAD

**Issue by xg787** [Sinytra/Connector#785] opened 2024-01-28 01:28 UTC
### Mod Name

ULTRACRAFT 

### Mod Homepage

https://modrinth.com/mod/absolute-ultracraft

### Minecraft version

1.20.1

### Describe the bug

server crash on startup

### Steps to reproduce

1.add mod to server
2.start server
3.crash
...

### Logs

https://gist.github.com/xg787/370d27bbc4372a2bd31c2e90ef7e2f37

### Additional context

using only connector beta 35

**Comment by Su5eD** [comment] 2024-01-28 09:00
Duplicate of #784

**Closed** 2024-01-28 09:00 UTC
Labels: compat
