### ISSUE TITLE
incompatibility with flashback mod - neoforge 1.21.1

### ISSUE THREAD

**Issue by TheVirusNVGM** [Sinytra/Connector#1358] opened 2024-08-23 11:24 UTC
### Mod Name

flashback

### Mod Homepage

https://modrinth.com/mod/flashback

### Minecraft version

1.21.1

### Describe the bug

seems to be complaining that client.gui is incompatible, I don’t know for sure

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/TheVirusNVGM/50eaed24110e94b6363cc72a9ad5b3c1

**Comment by Su5eD** [comment] 2024-08-23 15:12
Duplicate of #1353

**Closed as not planned by Su5eD** 2024-08-23 15:12 UTC
Labels: duplicate
