### ISSUE TITLE
Imcompatible with C2M

### ISSUE THREAD

**Issue by Kevenpvp** [Sinytra/Connector#635] opened 2023-12-22 22:30 UTC
### Mod Name

C2M

### Mod Homepage

https://modrinth.com/mod/c2me-fabric/version/0.2.0+alpha.11.39+23w51b

### Describe the bug

It crashed when trying runnin both

### Steps to reproduce

1. Download C2M on 1.20.1
2. Run the game
3. See the crash
...

### Logs

https://pastebin.com/Bn5VGCq6

### Additional context

It doenst crash if you set NoTickViewDistance to false on C2M configs file, but will still crash if you join world

**Comment by Su5eD** [comment] 2023-12-22 22:44
Duplicate of #88

**Closed by Su5eD** 2023-12-22 22:44 UTC
Labels: compat
