### ISSUE TITLE
Incompat with Gravity Changer

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#878] opened 2024-03-03 00:28 UTC
### Mod Name

Gravity Changer

### Mod Homepage

https://modrinth.com/mod/gravity-api-fork

### Minecraft version

1.20.1

### Describe the bug

crash at the start

### Steps to reproduce

1. download ffapi, connector, Gravity Changer and cloth-config
2. Run
3. See

### Logs

https://pastebin.com/Q9eKAc3X

**Comment by Su5eD** [comment] 2024-03-03 08:28
Duplicate of #135

**Closed by Su5eD** 2024-03-03 08:28 UTC
Labels: compat
