### ISSUE TITLE
Incompatibility with new version of Controlify mod (2.0.0 beta)

### ISSUE THREAD

**Issue by Axi0L** [Sinytra/Connector#1133] opened 2024-06-07 18:30 UTC
### Mod Name

Controlify

### Mod Homepage

https://modrinth.com/mod/controlify

### Minecraft version

1.20.1

### Describe the bug

Mod initializes, but gamepad controls and config screen don't work

### Steps to reproduce

Usual installation
1. Install connector, extras, ffapi, controlify
2. Install yacl (i used 3.4.2 forge version, 3.4.4 always crash when I try to edit fabric mods)
3. Enter game and try to control it with gamepad or open it's config screen (options - controls - controller). It will not work

How to make mod work
4. Instead of beta versions install controlify 1.6.0
5. Open the game with it and download libraries, calibrate controller
6. Close the game
7. Replace controlify 1.6.0 with newer versions
8. Open minecraft again and it will work

### Logs

https://gist.github.com/Axi0L/3fc9dd6e370575f03f089e892ddbcda5

### Additional context

After I replaced version back and forward gamepad worked. Then I deleted controlify.json and open minecraft again, I got the same issue I had at the beginning.

**Comment by Su5eD** [comment] 2024-06-07 20:40
Duplicate of https://github.com/Sinytra/Connector/issues/971

**Closed by Su5eD** 2024-06-07 20:40 UTC
Labels: compat
