### ISSUE TITLE
No performance mods avaible

### ISSUE THREAD

**Issue by fryly9** [Sinytra/Connector#636] opened 2023-12-22 22:32 UTC
### Mod Name

Optifine

### Mod Homepage

optifine.net

### Describe the bug

Minecraft crashes with error code 1 when I have optifine installed.

### Steps to reproduce

1. Download optifine for 1.20.1
2. Open minecraft
3. Minecraft crashes
...

### Logs

fas

**Comment by Su5eD** [comment] 2023-12-22 22:43
Duplicate of #111

**Closed by Su5eD** 2023-12-22 22:43 UTC
Labels: compat
