### ISSUE TITLE
Incompatibility w/ Hephaestus

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#245] opened 2023-09-12 19:00 UTC
### Mod Name

Hephaestus

### Mod Homepage

https://modrinth.com/mod/hephaestus

### Describe the bug

Game crashes

### Logs

https://crashy.net/22e54e9a-6c57-4474-9ee4-05c7624a7dfa

**Comment by Su5eD** [comment] 2023-09-12 19:02
Duplicate of #74

**Closed by Su5eD** 2023-09-12 19:02 UTC
Labels: compat
