### ISSUE TITLE
Incompatibility with Cardinal Components

### ISSUE THREAD

**Issue by aking4125** [Sinytra/Connector#136] opened 2023-08-28 14:28 UTC
### Mod Name

Cardinal Components

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/cardinal-components

### Describe the bug

crash on startup

### Steps to reproduce

1. Forge 47.1.3 with Connector and Forgified fabric API
2. Cardinal Components
3. Launch and crash

### Logs

Debug log: https://pastebin.com/tkdTy1Mx Prism Log: https://pastebin.com/ZYmmJve3

**Comment by Lolothepro** [comment] 2023-08-28 14:29
duplicate of #115

**Comment by coco875** [comment] 2023-08-28 14:30
it will be fix in beta10

**Comment by Xplodin** [comment] 2023-10-06 06:24
this issue has come back with beta 17

**Comment by rainysux** [comment] 2023-10-06 06:35
I personally have this mod and run it fine, a mod incompatibility possibly?

**Comment by Xplodin** [comment] 2023-10-06 06:36
possible. it worked fine before I updated mods
Does it work with mekanism+ addons

**Comment by Xplodin** [comment] 2023-10-06 06:52
going to connector 15 fixed the issue.
something prolly broke between 15 and 17

**Closed** 2023-10-07 12:36 UTC
Labels: compat
