### ISSUE TITLE
Synitra connector or Forgified Fabric API Issue 1.21.1

### ISSUE THREAD

**Issue by llAlexiussll** [Sinytra/Connector#1317] opened 2024-08-10 20:54 UTC
### Mod Name

Synitra connector or Forgified Api

### Mod Homepage

https://modrinth.com/mod/connector/version/2.0.0-beta.1+1.21 https://modrinth.com/mod/forgified-fabric-api/version/0.101.2+2.0.10+1.21

### Minecraft version

1.21.1

### Describe the bug

im just try to run minecraft using synitra connector and it dosent even open

### Steps to reproduce

1.
2.
3.
...

### Logs

https://gist.github.com/llAlexiussll/2568c9a6897b23850a4a20fbb28b9257

### Additional context

[1.21.1 Synitra Connector crash report.txt](https://github.com/user-attachments/files/16570871/1.21.1.Synitra.Connector.crash.report.txt)

**Comment by Su5eD** [comment] 2024-08-10 21:25
Duplicate of https://github.com/Sinytra/ForgifiedFabricAPI/issues/143

**Closed as not planned by Su5eD** 2024-08-10 21:25 UTC
Labels: duplicate
