### ISSUE TITLE
Continuity-3.0.0-beta.5 stopped running due to a mixins conflict with Connector Extras Continuity Compat

### ISSUE THREAD

**Issue by Tapacywka** [Sinytra/Connector#1092] opened 2024-05-16 08:59 UTC
### Mod Name

Continuity

### Mod Homepage

https://modrinth.com/mod/continuity

### Minecraft version

1.20.1

### Describe the bug

Continuity-3.0.0-beta.5 stopped running due to a mixins conflict with Connector Extras Continuity Compat

### Steps to reproduce

1. Install Connector, Connector Extras, Forgified Fabric API, Lazurite, Embeddium and Continuity.
2. Try to get into the game.

### Logs

https://mclo.gs/npHMGn5

### Additional context

It looks like an update to the Connector Extras Continuity Compat is required.
There is no changelog on the Continuity page itself,
and its github page hasn't been updated for a long time.

**Comment by Su5eD** [comment] 2024-05-16 10:54
Duplicate of Sinytra/ConnectorExtras#38

**Closed by Su5eD** 2024-05-16 10:54 UTC
Labels: compat
