### ISSUE TITLE
issues: “beta36的connector，0.91.0的fabric api和dash loader模组不兼容，没有崩溃报告，只有日志”

### ISSUE THREAD

**Issue by 1111317** [Sinytra/Connector#832] opened 2024-02-13 08:15 UTC
### Mod Name

issues: “beta36的connector，0.91.0的fabric api和dash loader模组不兼容，没有崩溃报告，只有日志”

### Mod Homepage

issues: “beta36的connector，0.91.0的fabric api和dash loader模组不兼容，没有崩溃报告，只有日志”

### Minecraft version

1.20.1

### Describe the bug

issues: “beta36的connector，0.91.0的fabric api和dash loader模组不兼容，没有崩溃报告，只有日志”

### Steps to reproduce

[2024-02-13-1.log](https://github.com/Sinytra/Connector/files/14257925/2024-02-13-1.log)

### Logs

issues: “beta36的connector，0.91.0的fabric api和dash loader模组不兼容，没有崩溃报告，只有日志”

### Additional context

issues:
“beta36的connector，0.91.0的fabric api和dash loader模组不兼容，没有崩溃报告，只有日志”

**Comment by coco875** [comment] 2024-02-13 08:18
duplicate of https://github.com/Sinytra/Connector/issues/515 an alternative can be modernfix who have more optimisation and include optimisation of dashloader

**Comment by Su5eD** [comment] 2024-02-13 13:02
Closing as duplicate of #515

**Closed by Su5eD** 2024-02-13 13:02 UTC
Labels: compat

**Comment by 1111317** [comment] 2024-02-15 11:03
> #515 的副本 替代方案可以是 ModernFix，他们有更多的优化，包括 Dashloader 的优化
On a 300+ mod modpack, Modernfix still doesn't start up half as fast as Dash Loader"

**Comment by coco875** [comment] 2024-02-15 11:13
I don't exaclty know how moderfix and dashloader are different but I know that modernfix his primerly goal is to optmise minecraft in general not only the load so maybe dashloader make some compromise to previege more the launch speed then other part who can make a less better experience, like tps, fps read/write disc etc

**Comment by 1111317** [comment] 2024-02-15 14:09
> 我不知道 moderfix 和 dashloader 有何不同，但我知道 modernfix 的首要目标是优化 Minecraft，而不仅仅是负载，所以也许 dashloader 会做出一些妥协，以抢占更多的启动速度，然后是其他可以提供不太好体验的部分，如 tps、fps 读/写光盘等

Anyway, I still hope to use Dash Loader on the Forge end to achieve extremely fast startup speed in the integration package of hundreds of modules, but Dash Loader is not willing to make the Forge version officially, as it really helps with startup acceleration

**Comment by coco875** [comment] 2024-02-15 14:16
the issue is open so it will fix this one days
