### ISSUE TITLE
Using the Sinytra Connector and Blueprint will render Continuity ineffective.

### ISSUE THREAD

**Issue by fszsxcylcyl** [Sinytra/Connector#1159] opened 2024-06-14 09:43 UTC
### Mod Name

Blueprint

### Mod Homepage

https://modrinth.com/mod/blueprint

### Minecraft version

1.20.1

### Describe the bug

Using the Sinytra Connector and Blueprint will render Continuity ineffective.

### Steps to reproduce

![2024-06-14_17 34 21](https://github.com/Sinytra/Connector/assets/76814391/d4672897-7062-4e63-8621-77420c174443)

...

### Logs

https://gist.github.com/fszsxcylcyl/0606af068f4e85d1259341c58662b1c2

**Comment by kakashi1464** [comment] 2024-06-14 09:51
duplicate of #1001

**Closed** 2024-06-14 11:56 UTC
Labels: compat
