### ISSUE TITLE
Origins mod incompatibility

### ISSUE THREAD

**Issue by Domiiih** [Sinytra/Connector#161] opened 2023-09-01 10:11 UTC
### Mod Name

Origins

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/origins/files

### Describe the bug

I'm trying to use Fabric Origins on 1.20.1, but Minecraft crashes while loading. I want to use it with Forge mods, but even if I try to use it with no Forge mods (so only Origins, Fabric API and Connector) it crashes.

### Steps to reproduce

1 .Start the game with mods
2. Game crashes on loading screen
3.
...

### Logs

https://pastebin.com/jixb0JMk

**Comment by Bloodpoison** [comment] 2023-09-06 15:10
any news on Origins Comp? its the Only Fabric mod i rlly want hoping this gets done :D

**Comment by Fiz-Victor** [comment] 2023-09-06 15:48
Duplicate of #46

**Comment by Su5eD** [comment] 2023-09-06 16:04
The current issue regarding reach entity attributes is the same, yes, but there are still further possible issues with origins' mixins, so I'll keep this open.

**Comment by sunfirecats** [comment] 2023-09-09 23:59
is this still a issue?

**Comment by PrelawAverage** [comment] 2023-09-11 04:24
Yeah i hope this gets fixed! Love the mod!

**Comment by coco875** [comment] 2023-09-12 10:24
the port of origins for forge is now in 1.20.1 so you can use it instead

**Comment by PrelawAverage** [comment] 2023-09-16 20:05
Yeah but the fabric version has all the addons that make origins mod so good!

**Comment by MerchantPug** [comment] 2023-12-06 01:10
As an Origins addon developer for both Origins Forge (I'm a maintainer for it too btw) and Origins Fabric, I'll give a heads up for something that Origins Fabric needs to fix on their end for true Connector compat.

Currently, Origins Fabric changes ItemStacks using mixins, which I think will break capabilities according to EdwinMindcraft, the dev of Origins Forge.

Use this information as you will.

**Comment by MerchantPug** [comment] 2023-12-06 01:16
I also have another fun fact about Origins Addons for you all.

Half of them aren't really addons, they're just datapacks, so they *should* be compatible with Origins Forge with Connector just loading them as a datapack.

The main two that are Fabric only are true addons tho, so they won't be. These two being Extra Origins and Mob Origins.

**Comment by Su5eD** [comment] 2023-12-08 12:45
I've added the necessary patches to fix mixin conflicts in Origins fabric and tested them to work on Forge 47.1.3. However, as you've mentioned, addons might still be incompatible. Therefore I strongly recommend using the Forge port of Origins when possible.

**Comment by mimi-min** [comment] 2023-12-16 12:58
> I also have another fun fact about Origins Addons for you all.
> 
> Half of them aren't really addons, they're just datapacks, so they _should_ be compatible with Origins Forge with Connector just loading them as a datapack.
> 
> The main two that are Fabric only are true addons tho, so they won't be. These two being Extra Origins and Mob Origins.

Could you maybe elaborate on this? I'm not very familiar with datapacks, but if I could get "[Classes](https://www.curseforge.com/minecraft/mc-mods/origins-classes)" working I would be very happy!

**Comment by MerchantPug** [comment] 2023-12-17 03:09
> > I also have another fun fact about Origins Addons for you all.
> > Half of them aren't really addons, they're just datapacks, so they _should_ be compatible with Origins Forge with Connector just loading them as a datapack.
> > The main two that are Fabric only are true addons tho, so they won't be. These two being Extra Origins and Mob Origins.
> 
> Could you maybe elaborate on this? I'm not very familiar with datapacks, but if I could get "[Classes](https://www.curseforge.com/minecraft/mc-mods/origins-classes)" working I would be very happy!

# Classes is also an exception to this data pack rule, so that's not one that'll work.

But for anybody who's interested. Data packs are a way to add content to the game through your world folder, mods can also utilise data packs for specific content. Origins is a very data driven mod, and so you can create content without making an addon through data packs. However, people realised you could just put a data pack into a mod's workspace, and suddenly it's an "addon" now.

Connector should be able to load up these datapack only addons, as they do not utilise any Java code, and have them function with Origins Forge.

**Closed** 2023-12-17 20:17 UTC
Labels: compat, mixin conflict
