### ISSUE TITLE
Does NOT work with Mythic Upgrades

### ISSUE THREAD

**Issue by KneckeKneck** [Sinytra/Connector#1156] opened 2024-06-13 10:07 UTC
### Mod Name

Mythic Upgrades

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mythic-upgrades-forge

### Minecraft version

1.20.1

### Describe the bug

Game Crashes on launch giving exit Code: 1

### Steps to reproduce

1.Install Sinytra Connector
2.Install owo-lib
3.Install Mythic Upgrades
4.Launch the Game
5.Crashes

### Logs

N/A

**Comment by Su5eD** [comment] 2024-06-13 11:18
Duplicate of #1065

**Closed by Su5eD** 2024-06-13 11:18 UTC
Labels: compat
