### ISSUE TITLE
[1.20.1] Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method setAdditionalWindowHints(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in sodium.mixins.json:core.WindowMixin from mod sodium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap sodium-fabric-refmap.json

### ISSUE THREAD

**Issue by TeQTabanca** [Sinytra/Connector#1324] opened 2024-08-12 19:21 UTC
### Mod Name

sodium-fabric-0.5.8+mc1.20.1

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sodium/download/5092241

### Minecraft version

1.20.1 (LTS)

### Describe the bug

The game gives an error while loading.

### Steps to reproduce

1.Start game

### Logs

https://gist.github.com/TeQTabanca/a4fdc2dd5fb0c1c790f0e370641510f8

**Comment by coco875** [comment] 2024-08-12 19:22
sodium are not supported use embeddium instead of sodium alpha forge port on iris server

**Comment by TeQTabanca** [comment] 2024-08-12 19:27
> sodium are not supported use embeddium instead of sodium alpha forge port on iris server

To try nvidium-0.2.6-beta mode, sodium-fabric-0.5.8+mc1.20.1 mode was required.

**Comment by coco875** [comment] 2024-08-12 19:29
you can use fabric dependancy overide to get it work or use [acedium](https://github.com/ferriarnus/acedium) who are a unofficial port of nvidium for forge and embeddium

**Comment by Su5eD** [comment] 2024-08-12 19:55
Duplicate of #71

**Closed as not planned by Su5eD** 2024-08-12 19:55 UTC
Labels: duplicate
