### ISSUE TITLE
Crash on startup, probably caused by Andromeda

### ISSUE THREAD

**Issue by ChromaPIE** [Sinytra/Connector#1021] opened 2024-04-21 09:45 UTC
### Mod Name

Andromeda

### Mod Homepage

https://modrinth.com/mod/andromeda

### Minecraft version

1.20.1

### Describe the bug

Crash on startup. The error screen reports that it might be caused by Andromeda
`Caused by 0: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to execute task me/melontini/andromeda/common/mixin/SubCategoryListEntryMixin.class`

### Logs

https://mclo.gs/xLuT4bN

**Comment by ChromaPIE** [comment] 2024-04-22 02:34
Using the latest dev build and got this crash: https://mclo.gs/S2lBIBe

**Comment by ChromaPIE** [comment] 2024-04-22 09:32
It's possibly caused by another mod(s). got this crash during my migration test. now i can actually go to the main menu.
so if this crash log isn't directly exposing potential compatibility problem with Andromeda i think this can be closed for now. @Su5eD

**Comment by Su5eD** [comment] 2024-04-22 16:29
I'll look into it

**Comment by ChromaPIE** [comment] 2024-04-24 09:42
it's still kind of problematic. like it prints a lot of errors when the game's booting up, and now when trying to enter a world the game crashes with [this](https://mclo.gs/46wHSbk) report.

the whole log: https://mclo.gs/33T6C31

**Comment by melontini** [comment] 2024-04-24 16:09
I personally cannot reproduce the crash and log spam on an Andromeda-only instance.
Log spam was supossed to be fixed in a previous release of Connector. (I'd assume one of the 6 quantillion optimization mods had something to do with this)

As per the crash, on Fabric this can only happen if you ignore the "Requires Restart" popup, but I know that AM crashes Quilt, because QSL replaces the return of the getContents method. Maybe something like this happened here.

**Comment by xXMolgadoGamer01Xx** [comment] 2024-04-27 17:14
Ok, so since my report was closes as it was a duplicate of this one, then I'll leave my crash report here.
Hopefully it helps to fix this crash.
Crash report: https://pastebin.com/4wSfddDj

**Closed** 2024-08-08 13:45 UTC
Labels: compat, mixin conflict, 1.21.x
