### ISSUE TITLE
Carpet Incompatible

### ISSUE THREAD

**Issue by ghost** [Sinytra/Connector#1440] opened 2024-09-28 08:32 UTC
### Mod Name

Fabric-Carpet

### Mod Homepage

https://modrinth.com/mod/carpet

### Minecraft version

1.21.1

### Describe the bug

 The server throws an error when I run it with the carpet mod

### Steps to reproduce

1.
2.
3.
...

### Logs

https://paste.ubuntu.com/p/35PHCcyFpV/

**Comment by Su5eD** [comment] 2024-09-28 11:24
Duplicate of https://github.com/Sinytra/Connector/issues/296

**Closed as not planned by Su5eD** 2024-09-28 11:24 UTC
Labels: duplicate
