### ISSUE TITLE
Crashes when installed CreativeCore Forge & Fabric

### ISSUE THREAD

**Issue by AceCommander09** [Sinytra/Connector#148] opened 2023-08-29 21:31 UTC
### Mod Name

CreativeCore

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/creativecore

### Describe the bug

Just crashes immediately on Minecraft boot.

### Steps to reproduce

1. Install CreativeCore Forge or Fabric
2. Run Minecraft
3. Crash
...

### Logs

07:26:13.430 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-rendering-data-attachment-v1-0.3.34+561530ec77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.431 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-networking-api-v1-1.3.10+243b429977.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.431 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-sound-api-v1-1.0.12+4f23bd8477.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.431 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-particles-v1-1.1.1+a581c7f877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.431 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-message-api-v1-5.1.7+ff2512b877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.431 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-content-registries-v0-4.0.9+afab492177.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.431 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-lifecycle-events-v1-2.2.21+afab492177.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.431 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-transitive-access-wideners-v1-4.3.0+1880499877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.432 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-data-generation-api-v1-12.2.2+032a79a877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.432 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-events-interaction-v0-0.6.1+25d9948677.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.432 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-key-binding-api-v1-1.0.36+561530ec77.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.432 net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer main Found mod file fabric-client-tags-api-v1-1.1.1+5d6761b877.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@1a8df0b3 07:26:13.808 dev.su5ed.sinytra.connector.locator.DependencyResolver main Dependency resolution found 0 candidates to load 07:26:15.837 launcher main  Exception in thread "main" java.lang.module.ResolutionException: Modules creativecore and dev.su5ed.sinytra.connector export package net.fabricmc.api to module citadel 	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901) 	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815) 	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736) 	at java.base/java.lang.module.Resolver.finish(Resolver.java:380) 	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140) 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) 07:26:15.837 monitor Process Monitor Process crashed with exit code 1

### Additional context

Modpack: https://www.mediafire.com/file/6ymj853vfaxs5j6/mods_with_error.zip/file

**Comment by Su5eD** [comment] 2023-08-29 21:34
Duplicate of #122

**Closed by Su5eD** 2023-08-29 21:34 UTC
Labels: compat
