### ISSUE TITLE
Incompability with Bewitchment

### ISSUE THREAD

**Issue by ItzBurning2023** [Sinytra/Connector#181] opened 2023-09-04 17:26 UTC
### Mod Name

Betwitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Describe the bug

I tried to load the mod by itself and it just doesn't work, my game crashes

### Steps to reproduce

These are the mods I used: 
![image](https://github.com/Sinytra/Connector/assets/143913105/3087241a-f227-4220-a302-45bd681dacc7)
and here is the log: 
[crash-2023-09-04_13.17.50-fml.txt](https://github.com/Sinytra/Connector/files/12515610/crash-2023-09-04_13.17.50-fml.txt)

### Logs

*

### Additional context

*

**Comment by Su5eD** [comment] 2023-09-04 17:33
Duplicate of #172

**Closed by Su5eD** 2023-09-04 17:33 UTC
Labels: compat
