### ISSUE TITLE
Crashwhen loading mythic metals

### ISSUE THREAD

**Issue by NULLIFICATED** [Sinytra/Connector#220] opened 2023-09-09 11:17 UTC
### Mod Name

Mythic Metals

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/mythicmetals

### Describe the bug

Crash while minecraft mod loading

### Steps to reproduce

1.
2.
3.
...

### Logs

https://pastebin.com/qMbW7XGQ

**Comment by Su5eD** [comment] 2023-09-09 11:19
Duplicate of #46

**Closed** 2023-09-09 11:19 UTC
Labels: compat
