### ISSUE TITLE
Crash with Polymer

### ISSUE THREAD

**Issue by digi2303** [Sinytra/Connector#1378] opened 2024-08-30 14:19 UTC
### Mod Name

Polymer

### Mod Homepage

https://modrinth.com/mod/polymer

### Minecraft version

1.21.1

### Describe the bug

When I try to open minecraft with Polymer game crash.

### Steps to reproduce

1.Install Polymer Connector, Connector Extra, FFAPI
2.Open Minecraft
3.Game crash

### Logs

https://gist.github.com/digi2303/05fe8523e0ce2d112989462f973b4aa5

### Debug

https://gist.github.com/digi2303/a02490258fc51183fa76c59d048abcf1

### Crash Report

https://gist.github.com/digi2303/6174cf02d68632a91dcff3caeec47b84

**Comment by Su5eD** [comment] 2024-09-02 09:18
Duplicate of #1333

**Closed as not planned by Su5eD** 2024-09-02 09:18 UTC
Labels: duplicate
