### ISSUE TITLE
atm9 with spectrum for 1.20.1

### ISSUE THREAD

**Issue by MaboroshiNoLeneya** [Sinytra/Connector#634] opened 2023-12-22 17:23 UTC
### Mod Name

Spectrum

### Mod Homepage

https://github.com/DaFuqs/Spectrum

### Describe the bug

when launching the game without any fabric mods it works fine, however when loading spectrum alone with its necessairy libraries / dependencies its crashing

### Steps to reproduce

1. Download ATM9-0.2.32
2. Download and add Sinytra Connector and Forgified API
3. Download and add Spectrum, Trinkets, Revelationary, Cardinal Components API
4. Launch game -> crash
5. disabled Spectrum, Trinkets, Revelationary, Cardinal Components API
6. Launch game again -> runs through
...

### Logs

https://pastebin.com/ReperMsL ; https://pastebin.com/GdKKQ8WG ; debug log: https://gist.github.com/MaboroshiNoLeneya/02fbfb57816e02285ad0d1adb1fe9565

**Comment by Su5eD** [comment] 2023-12-22 17:28
Duplicate of #592

**Closed by Su5eD** 2023-12-22 17:28 UTC
Labels: compat
