### ISSUE TITLE
game crashes with oculus and rubidium

### ISSUE THREAD

**Issue by MarsliZiya** [Sinytra/Connector#252] opened 2023-09-13 15:49 UTC
### Describe the bug

mods worked earlier fine, drag the mods out of folder then back in and then it started to crash

### Steps to reproduce

1.rubidium 0.6.5 and oculus 1.6.4 works fine
2.copied the mod folder into new prodile with exact same folders and mod versions
3.game crashes
...

### Logs
[crash-2023-09-13_17.57.09-client.txt](https://github.com/Sinytra/Connector/files/12599608/crash-2023-09-13_17.57.09-client.txt)
[crash-2023-09-13_17.55.03-client.txt](https://github.com/Sinytra/Connector/files/12599614/crash-2023-09-13_17.55.03-client.txt)

_No response_

**Comment by Su5eD** [comment] 2023-09-13 16:05
Please provide your debug.log

**Comment by RoomAlex68** [comment] 2023-09-13 16:08
It works fine for me

**Comment by MarsliZiya** [comment] 2023-09-13 16:13
> It works fine for me

can you pls say the versions of the FAAPI and connector mod and of rubidium oculus

**Comment by MarsliZiya** [comment] 2023-09-13 16:14
> Please provide your debug.log

https://github.com/Sinytra/Connector/files/12599741/latest.log

**Comment by MarsliZiya** [comment] 2023-09-13 16:21
> Please provide your debug.log

this is the log from my duplicated profile i tried quite much to fix it but no chance

**Comment by Su5eD** [comment] 2023-09-13 16:36
> [18:31:09] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'architectury', Requested by: 'mtr', Expected range: '[1.26.37,)', Actual version: '[MISSING]'

This says you're missing a dependency - architectury

**Comment by Vexonek** [comment] 2023-09-14 09:34
Reinstall forge it might work

**Comment by RoomAlex68** [comment] 2023-09-14 20:44
> can you pls say the versions of the FAAPI and connector mod and of rubidium oculus

I used rubidium 0.6.5 and oculus 1.6.4 and Connecter Beta 13 and Forgefied Fabric API 1.9.11

**Comment by gitguette** [comment] 2023-09-17 02:15
since when did connector work with rubidium 0.6.5???

**Comment by Su5eD** [comment] 2023-09-18 17:08
Closing as cannot reproduce; and no log has been provided

**Closed by Su5eD** 2023-09-18 17:08 UTC
Labels: bug
