### ISSUE TITLE
[1.20.1] Simply Swords and Mythic Metals not working how they should 

### ISSUE THREAD

**Issue by Starexify** [Sinytra/Connector#987] opened 2024-04-07 09:30 UTC
### Mod Name

Simply Swords

### Mod Homepage

https://modrinth.com/mod/simply-swords

### Minecraft version

1.20.1

### Describe the bug

Simply Swords Fabric crashes with Connector.

### Steps to reproduce

1. Install Simply Swords (Fabric will crash) (Forge is not gonna add the support for Mythic Metals) alongside Connector and Mythic Metals (+ It's dependencies)

### Logs

I will place the logs down with information

### Additional context

When trying Simply Swords for Fabric:
[crash-2024-04-07_11.21.23-client.txt](https://github.com/Sinytra/Connector/files/14896586/crash-2024-04-07_11.21.23-client.txt)
[latest.log](https://github.com/Sinytra/Connector/files/14896588/latest.log)

When trying Simply Swords for Forge:
vs Simply Swords Fabric (on normal Fabric):
[latest.log](https://github.com/Sinytra/Connector/files/14896607/latest.log) [Log from Forge may help maybe]

On Forge:
![image_2024-04-07_112945575](https://github.com/Sinytra/Connector/assets/80699736/9dd709d5-681f-4a56-a1ec-9e1c1154c267)

On Fabric (how it should look on forge aswell):
![image](https://github.com/Sinytra/Connector/assets/80699736/bf200ea0-d3b1-4f34-8b7c-e91df3c8a3e6)
![image](https://github.com/Sinytra/Connector/assets/80699736/26f8f898-58ce-4849-815c-f4108f3aa69a)

**Comment by Su5eD** [comment] 2024-04-07 09:42
Duplicate of #853

**Closed by Su5eD** 2024-04-07 09:42 UTC
Labels: compat

**Comment by Starexify** [comment] 2024-04-07 09:46
> Duplicate of #853

How exactly "hiding" in : https://github.com/Sinytra/Connector/issues/430#issuecomment-1817474640
And also would that add the support between mythic metals and simply swords for forge somehow? Since that's the main point of this
