### ISSUE TITLE
Wilder wilds crash on startup

### ISSUE THREAD

**Issue by DemonSlayer112** [Sinytra/Connector#1073] opened 2024-05-09 05:14 UTC
### Mod Name

Wilder Wilds

### Mod Homepage

https://modrinth.com/mod/wilder-wild/version/2.4.1-mc1.20.1

### Minecraft version

1.20.1

### Describe the bug

It crashes, can't tell why myself.

### Steps to reproduce

1. I tried installing various dependancy mods but idk if it needs more or which it does need.
2. tried various mods that may be a dependancy but im not sure how to tell
...

### Logs

https://pastebin.com/FmPXLBSn

### Additional context

Forge Version: 47.2.0
Connector Version: Connector-1.0.0-beta.43+1.20.1
Forgeified Api Version: fabric-api-0.92.1+1.11.8+1.20.1

**Comment by Su5eD** [comment] 2024-05-09 06:48
Duplicate of #1055

**Closed by Su5eD** 2024-05-09 06:48 UTC
Labels: compat
